import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';

/**
 * One `content.ts` found under `app/`.
 */
export interface DiscoveredPage {
    name: string;
    path: string;
    file: string;
}

const CONTENT_FILES = ['content.ts', 'content.tsx', 'content.js', 'content.mjs'];

/**
 * Next's route path for a folder: route groups and parallel slots fall away,
 * intercepting markers go, and the rest is the URL.
 */
export const routePathOf = (appDir: string, folder: string): string => {
    const segments = relative(appDir, folder)
        .split(sep)
        .filter((segment) => segment !== '' && segment !== '.')
        .filter((segment) => !(segment.startsWith('(') && segment.endsWith(')')))
        .filter((segment) => !segment.startsWith('@'))
        .map((segment) => segment.replace(/^\(\.{1,3}\)|^\(\.\.\.\)/, ''));
    return `/${segments.join('/')}`;
};

const NAME_PATTERN = /\bpage\s*\(\s*\{[\s\S]*?\bname\s*:\s*(['"`])([A-Za-z_$][\w$]*)\1/;

/**
 * The page name a `content.ts` declares, read from its source so discovery
 * runs nothing.
 */
export const pageNameIn = (source: string): string | undefined => NAME_PATTERN.exec(source)?.[2];

/**
 * The `app` directory a project uses, when it has one.
 */
export const findAppDir = (cwd = process.cwd()): string | undefined =>
    ['src/app', 'app'].map((candidate) => resolve(/* turbopackIgnore: true */ cwd, candidate)).find((candidate) => existsSync(candidate));

/**
 * Every page under `appDir`, in path order. Two pages sharing a name is an
 * error that names both files.
 */
export const discoverPages = (appDir: string): DiscoveredPage[] => {
    if (!existsSync(appDir)) return [];
    const found: DiscoveredPage[] = [];
    const walk = (folder: string): void => {
        for (const entry of readdirSync(folder).sort()) {
            const full = join(folder, entry);
            if (statSync(full).isDirectory()) {
                if (entry === 'node_modules' || entry.startsWith('.')) continue;
                walk(full);
                continue;
            }
            if (!CONTENT_FILES.includes(entry)) continue;
            const name = pageNameIn(readFileSync(full, 'utf8'));
            if (name === undefined) {
                throw new Error(`${full} has no \`page({ name: '...' })\` with a literal name. Discovery reads the name from the source.`);
            }
            found.push({
                name,
                path: routePathOf(appDir, folder),
                file: full,
            });
        }
    };
    walk(appDir);
    const byName = new Map<string, DiscoveredPage>();
    for (const page of found) {
        const existing = byName.get(page.name);
        if (existing !== undefined) {
            throw new Error(`Two pages are named '${page.name}':\n  ${existing.file}\n  ${page.file}\nGive one of them another name.`);
        }
        byName.set(page.name, page);
    }
    return found.sort((left, right) => left.path.localeCompare(right.path));
};

const importSpecifier = (from: string, to: string): string => {
    const spec = relative(dirname(from), to)
        .split(sep)
        .join('/')
        .replace(/\.(ts|tsx|js|mjs)$/, '');
    return spec.startsWith('.') ? spec : `./${spec}`;
};

/**
 * The module the config imports `pages` from: one import per page, keyed by
 * name with its path.
 */
export const renderPagesModule = (pages: readonly DiscoveredPage[], outputFile: string): string => {
    const lines = [
        '/**',
        ' * This file was automatically generated by kizuna.',
        ' * DO NOT MODIFY IT BY HAND. Instead, add or move a `content.ts` under `app/`,',
        ' * and re-run `kizuna generate` to regenerate this file.',
        ' */',
    ];
    for (const page of pages) lines.push(`import ${page.name} from '${importSpecifier(outputFile, page.file)}';`);
    lines.push('');
    lines.push('export const pages = {');
    for (const page of pages) {
        lines.push(`    ${page.name}: {`);
        lines.push(`        path: '${page.path}',`);
        lines.push(`        page: ${page.name},`);
        lines.push('    },');
    }
    lines.push('};');
    lines.push('');
    return lines.join('\n');
};

/**
 * Where the pages module goes by default: beside the app directory, as
 * `cms.pages.ts`.
 */
export const defaultPagesOutput = (appDir: string): string => join(dirname(appDir), 'cms.pages.ts');
