/**
 * This file was automatically generated by kizuna.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source kizuna config,
 * and re-run `kizuna generate` to regenerate this file.
 */
import type { nextAdapter } from '@kizunajs/next';
import type { mcpPlugin } from '@kizunajs/mcp';
import type { openApiPlugin } from '@kizunajs/openapi';
import type { cmsPlugin } from '@kizunajs/cms';
import type { app, editor } from './identities';

export interface Config {
    adapter: ReturnType<typeof nextAdapter>;
    auth: {
        identities: {
            editor: typeof editor;
            app: typeof app;
        };
    };
    plugins: [ReturnType<typeof mcpPlugin>, ReturnType<typeof openApiPlugin>, ReturnType<typeof cmsPlugin>];
}
