import type * as TypeScriptNamespace from 'typescript';

type TypeScriptModule = typeof TypeScriptNamespace;

interface Deprecation {
    message: string | undefined;
}

/**
 * TypeScript's own "is deprecated" code, so editors render these natively.
 */
const DEPRECATED_CODE = 6385;

/**
 * Kizuna's own, for a generated client that no longer matches its contract.
 */
const STALE_CLIENT_CODE = 900_001;

const GENERATED_MARKER = 'Generated by @ts-kizuna/';
const SOURCE_MARKER = /^\s*\*\s*Source:\s*(.+)$/m;
const REGENERATE_MARKER = /^\s*\*\s*Regenerate:\s*(.+)$/m;

function init(modules: { typescript: TypeScriptModule }): {
    create: (info: TypeScriptNamespace.server.PluginCreateInfo) => TypeScriptNamespace.LanguageService;
} {
    const typescript = modules.typescript;

    const findProperty = (
        object: TypeScriptNamespace.ObjectLiteralExpression,
        name: string
    ): TypeScriptNamespace.PropertyAssignment | undefined => {
        for (const property of object.properties) {
            if (!typescript.isPropertyAssignment(property)) continue;
            if (typescript.isIdentifier(property.name) && property.name.text === name) return property;
            if (typescript.isStringLiteral(property.name) && property.name.text === name) return property;
        }
        return undefined;
    };

    /**
     * Every form the contract accepts: `true`, a message, or `{ message?, date?, link? }`.
     */
    const declaredDeprecation = (expression: TypeScriptNamespace.Expression): Deprecation | undefined => {
        if (expression.kind === typescript.SyntaxKind.TrueKeyword) {
            return {
                message: undefined,
            };
        }
        if (typescript.isStringLiteral(expression)) {
            return {
                message: expression.text,
            };
        }
        if (typescript.isObjectLiteralExpression(expression)) {
            const messageProperty = findProperty(expression, 'message');
            const message =
                messageProperty && typescript.isStringLiteral(messageProperty.initializer) ? messageProperty.initializer.text : undefined;
            return {
                message,
            };
        }
        return undefined;
    };

    const metaObjectDeprecation = (meta: TypeScriptNamespace.ObjectLiteralExpression): Deprecation | undefined => {
        const deprecatedProperty = findProperty(meta, 'deprecated');
        return deprecatedProperty ? declaredDeprecation(deprecatedProperty.initializer) : undefined;
    };

    const metaChainDeprecation = (expression: TypeScriptNamespace.Expression): Deprecation | undefined => {
        let current: TypeScriptNamespace.Expression = expression;
        while (typescript.isCallExpression(current) && typescript.isPropertyAccessExpression(current.expression)) {
            if (current.expression.name.text === 'meta') {
                const argument = current.arguments[0];
                if (argument && typescript.isObjectLiteralExpression(argument)) {
                    const found = metaObjectDeprecation(argument);
                    if (found) return found;
                }
            }
            current = current.expression.expression;
        }
        return undefined;
    };

    /**
     * The route a `k.route({ … })` call declares, reached through whatever is
     * chained onto it.
     */
    const routeArgument = (expression: TypeScriptNamespace.Expression): TypeScriptNamespace.ObjectLiteralExpression | undefined => {
        let current: TypeScriptNamespace.Expression = expression;
        while (typescript.isCallExpression(current) && typescript.isPropertyAccessExpression(current.expression)) {
            if (current.expression.name.text === 'route') {
                const argument = current.arguments[0];
                return argument && typescript.isObjectLiteralExpression(argument) ? argument : undefined;
            }
            current = current.expression.expression;
        }
        return undefined;
    };

    const declarationDeprecation = (declaration: TypeScriptNamespace.Declaration): Deprecation | undefined => {
        if (!typescript.isPropertyAssignment(declaration)) return undefined;
        const initializer = declaration.initializer;
        const route = typescript.isObjectLiteralExpression(initializer) ? initializer : routeArgument(initializer);
        if (route) {
            if (!findProperty(route, 'method')) return undefined;
            const deprecatedProperty = findProperty(route, 'deprecated');
            return deprecatedProperty ? declaredDeprecation(deprecatedProperty.initializer) : undefined;
        }
        return metaChainDeprecation(initializer);
    };

    /**
     * Transient symbols on mapped and inferred types point at their authored
     * declaration through the internal `target`.
     */
    const resolveTargetSymbol = (symbol: TypeScriptNamespace.Symbol): TypeScriptNamespace.Symbol => {
        let current = symbol;
        const seen = new Set<TypeScriptNamespace.Symbol>();
        while (!seen.has(current)) {
            seen.add(current);
            const target = (current as { target?: TypeScriptNamespace.Symbol }).target;
            if (!target) break;
            current = target;
        }
        return current;
    };

    const symbolDeprecation = (symbol: TypeScriptNamespace.Symbol | undefined): Deprecation | undefined => {
        if (!symbol) return undefined;
        for (const candidate of [symbol, resolveTargetSymbol(symbol)]) {
            for (const declaration of candidate.getDeclarations() ?? []) {
                const found = declarationDeprecation(declaration);
                if (found) return found;
            }
        }
        return undefined;
    };

    const nodeAt = (node: TypeScriptNamespace.Node, position: number): TypeScriptNamespace.Node => {
        let match: TypeScriptNamespace.Node | undefined;
        node.forEachChild((child) => {
            if (!match && position >= child.getStart() && position < child.getEnd()) match = child;
        });
        return match ? nodeAt(match, position) : node;
    };

    const propertyAccessAt = (
        sourceFile: TypeScriptNamespace.SourceFile,
        position: number
    ): TypeScriptNamespace.PropertyAccessExpression | undefined => {
        for (const candidate of [position, position - 1]) {
            if (candidate < 0) continue;
            let current: TypeScriptNamespace.Node | undefined = nodeAt(sourceFile, candidate);
            while (current && !typescript.isPropertyAccessExpression(current)) current = current.parent;
            if (current) return current;
        }
        return undefined;
    };

    /**
     * Every file a contract was built from, walked through the program so the
     * import graph is the one TypeScript already resolved.
     */
    const contractSources = (program: TypeScriptNamespace.Program, entry: TypeScriptNamespace.SourceFile): string[] => {
        const seen = new Set<string>();
        const queue = [entry];

        while (queue.length > 0) {
            const file = queue.pop();
            if (!file || seen.has(file.fileName) || file.fileName.includes('node_modules')) continue;
            seen.add(file.fileName);

            for (const statement of file.statements) {
                if (!typescript.isImportDeclaration(statement) && !typescript.isExportDeclaration(statement)) continue;
                const specifier = statement.moduleSpecifier;
                if (!specifier || !typescript.isStringLiteral(specifier)) continue;
                if (!specifier.text.startsWith('.')) continue;

                const resolved = program
                    .getSourceFiles()
                    .find((candidate) => sameModule(candidate.fileName, file.fileName, specifier.text));
                if (resolved) queue.push(resolved);
            }
        }

        return [...seen];
    };

    const sameModule = (candidateFile: string, fromFile: string, specifier: string): boolean => {
        const directory = fromFile.slice(0, fromFile.lastIndexOf('/'));
        const withoutExtension = specifier.replace(/\.[cm]?js$/, '').replace(/\.[cm]?ts$/, '');
        const base = `${directory}/${withoutExtension}`.replace(/\/\.\//g, '/');
        return (
            candidateFile === `${base}.ts` ||
            candidateFile === `${base}.tsx` ||
            candidateFile === `${base}/index.ts` ||
            candidateFile === `${base}/index.tsx`
        );
    };

    const create = (info: TypeScriptNamespace.server.PluginCreateInfo): TypeScriptNamespace.LanguageService => {
        const languageService = info.languageService;

        const members = Object.create(null) as Record<string, unknown>;
        for (const key of Object.keys(languageService)) {
            const member = (languageService as unknown as Record<string, unknown>)[key];
            members[key] =
                typeof member === 'function' ? (member as (...callArguments: unknown[]) => unknown).bind(languageService) : member;
        }
        const proxy = members as unknown as TypeScriptNamespace.LanguageService;

        // Sticky per project: a new ts-kizuna install needs a TS server restart.
        let kizunaProject: boolean | undefined;
        const isKizunaProject = (program: TypeScriptNamespace.Program): boolean => {
            if (kizunaProject === undefined) {
                kizunaProject = program
                    .getSourceFiles()
                    .some((file) => file.fileName.includes('@ts-kizuna/') || file.text.includes('ts-kizuna'));
            }
            return kizunaProject;
        };

        const fileContext = (
            fileName: string
        ): { sourceFile: TypeScriptNamespace.SourceFile; checker: TypeScriptNamespace.TypeChecker } | undefined => {
            const program = languageService.getProgram();
            const sourceFile = program?.getSourceFile(fileName);
            if (!program || !sourceFile) return undefined;
            if (!isKizunaProject(program)) return undefined;
            return {
                sourceFile,
                checker: program.getTypeChecker(),
            };
        };

        /**
         * A generated client is stale when any file its contract was built from
         * has been written since. Compares modification times rather than
         * regenerating, which a language service has no business doing.
         */
        const staleClientDiagnostic = (
            sourceFile: TypeScriptNamespace.SourceFile,
            program: TypeScriptNamespace.Program
        ): TypeScriptNamespace.DiagnosticWithLocation | undefined => {
            const header = sourceFile.text.slice(0, 400);
            if (!header.includes(GENERATED_MARKER)) return undefined;

            const declared = SOURCE_MARKER.exec(header)?.[1]?.trim();
            if (declared === undefined) return undefined;

            const modifiedAt = (file: string): number => info.serverHost?.getModifiedTime?.(file)?.getTime() ?? 0;

            const generatedAt = modifiedAt(sourceFile.fileName);
            if (generatedAt === 0) return undefined;

            const directory = sourceFile.fileName.slice(0, sourceFile.fileName.lastIndexOf('/'));
            const entryPath = `${directory}/${declared}`.replace(/\/\.\//g, '/');
            const entry = program.getSourceFiles().find((candidate) => candidate.fileName === entryPath);
            if (!entry) return undefined;

            const newer = contractSources(program, entry).filter((file) => modifiedAt(file) > generatedAt);
            if (newer.length === 0) return undefined;

            const command = REGENERATE_MARKER.exec(header)?.[1]?.trim() ?? 'the generate command';
            const changed = newer[0]?.split('/').pop() ?? 'the contract';

            return {
                file: sourceFile,
                start: 0,
                length: Math.min(header.indexOf('*/') + 2, sourceFile.text.length),
                messageText: `This client is older than ${changed}. Run \`${command}\` to bring it up to date.`,
                category: typescript.DiagnosticCategory.Suggestion,
                code: STALE_CLIENT_CODE,
            };
        };

        proxy.getSuggestionDiagnostics = (fileName) => {
            const prior = languageService.getSuggestionDiagnostics(fileName);
            const context = fileContext(fileName);
            if (!context) return prior;
            const extra: TypeScriptNamespace.DiagnosticWithLocation[] = [];

            const program = languageService.getProgram();
            const stale = program ? staleClientDiagnostic(context.sourceFile, program) : undefined;
            if (stale) extra.push(stale);
            const visit = (node: TypeScriptNamespace.Node): void => {
                if (typescript.isPropertyAccessExpression(node)) {
                    const deprecation = symbolDeprecation(context.checker.getSymbolAtLocation(node.name));
                    if (deprecation) {
                        extra.push({
                            file: context.sourceFile,
                            start: node.name.getStart(context.sourceFile),
                            length: node.name.getWidth(context.sourceFile),
                            messageText: deprecation.message
                                ? `'${node.name.text}' is deprecated. ${deprecation.message}`
                                : `'${node.name.text}' is deprecated.`,
                            category: typescript.DiagnosticCategory.Suggestion,
                            code: DEPRECATED_CODE,
                            reportsDeprecated: true,
                        });
                    }
                }
                typescript.forEachChild(node, visit);
            };
            visit(context.sourceFile);
            // Loaded twice (tsconfig plus extension), the inner instance already reported these.
            const fresh = extra.filter(
                (candidate) => !prior.some((existing) => existing.start === candidate.start && existing.code === candidate.code)
            );
            return [...prior, ...fresh];
        };

        proxy.getQuickInfoAtPosition = (fileName, position) => {
            const prior = languageService.getQuickInfoAtPosition(fileName, position);
            if (!prior) return prior;
            const context = fileContext(fileName);
            if (!context) return prior;
            const node = nodeAt(context.sourceFile, position);
            if (!typescript.isIdentifier(node)) return prior;
            const deprecation = symbolDeprecation(context.checker.getSymbolAtLocation(node));
            if (!deprecation) return prior;
            if (prior.tags?.some((candidate) => candidate.name === 'deprecated')) return prior;
            const tag: TypeScriptNamespace.JSDocTagInfo = {
                name: 'deprecated',
                text: deprecation.message
                    ? [
                          {
                              kind: 'text',
                              text: deprecation.message,
                          },
                      ]
                    : [],
            };
            return {
                ...prior,
                tags: [...(prior.tags ?? []), tag],
            };
        };

        proxy.getCompletionsAtPosition = (fileName, position, options, formattingSettings) => {
            const prior = languageService.getCompletionsAtPosition(fileName, position, options, formattingSettings);
            if (!prior) return prior;
            const context = fileContext(fileName);
            if (!context) return prior;
            const access = propertyAccessAt(context.sourceFile, position);
            if (!access) return prior;
            const receiverType = context.checker.getTypeAtLocation(access.expression);
            for (const entry of prior.entries) {
                if (entry.kindModifiers?.includes('deprecated')) continue;
                const deprecation = symbolDeprecation(receiverType.getProperty(entry.name));
                if (!deprecation) continue;
                entry.kindModifiers = entry.kindModifiers ? `${entry.kindModifiers},deprecated` : 'deprecated';
            }
            return prior;
        };

        return proxy;
    };

    return {
        create,
    };
}

export = init;
