import { mkdtempSync, rmSync, utimesSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createRequire } from 'node:module';
import { afterEach, describe, expect, it } from 'vitest';
import ts from 'typescript';

const requireFromHere = createRequire(import.meta.url);
const init = requireFromHere('../dist/index.cjs') as typeof import('./index.cts');

const STALE_CLIENT_CODE = 900_001;

const directories: string[] = [];

afterEach(() => {
    while (directories.length > 0) rmSync(directories.pop()!, { recursive: true, force: true });
});

/**
 * A generated client beside the two files its contract was built from, so the
 * diagnostic has an import graph to walk rather than a single entry.
 */
const project = ({ routesNewer }: { routesNewer: boolean }) => {
    const directory = mkdtempSync(join(tmpdir(), 'kizuna-stale-'));
    directories.push(directory);

    const routes = join(directory, 'routes.ts');
    const contract = join(directory, 'contract.ts');
    const client = join(directory, 'client.ts');

    writeFileSync(routes, `export const routes = { name: 'ts-kizuna' };\n`);
    writeFileSync(contract, `import { routes } from './routes.js';\nexport const contract = { routes };\n`);
    writeFileSync(
        client,
        `/* eslint-disable */
/**
 * Generated by @ts-kizuna/fetch. Do not edit.
 *
 * Source: ./contract.ts
 * Regenerate: pnpm kizuna generate
 */
export const createClient = () => ({});
`
    );

    const old = new Date('2026-01-01T00:00:00Z');
    const recent = new Date('2026-06-01T00:00:00Z');

    utimesSync(contract, old, old);
    utimesSync(client, recent, recent);
    utimesSync(routes, routesNewer ? new Date('2026-09-01T00:00:00Z') : old, routesNewer ? new Date('2026-09-01T00:00:00Z') : old);

    return { directory, client, contract };
};

const diagnosticsFor = (directory: string, client: string, contract: string): ts.DiagnosticWithLocation[] => {
    const host: ts.LanguageServiceHost = {
        getScriptFileNames: () => [client, contract],
        getScriptVersion: () => '1',
        getScriptSnapshot: (fileName) =>
            ts.sys.fileExists(fileName) ? ts.ScriptSnapshot.fromString(ts.sys.readFile(fileName) ?? '') : undefined,
        getCurrentDirectory: () => directory,
        getCompilationSettings: () => ({ target: ts.ScriptTarget.ES2022, strict: true, skipLibCheck: true, noEmit: true }),
        getDefaultLibFileName: (options) => ts.getDefaultLibFilePath(options),
        fileExists: ts.sys.fileExists,
        readFile: ts.sys.readFile,
        readDirectory: ts.sys.readDirectory,
        directoryExists: ts.sys.directoryExists,
        getDirectories: ts.sys.getDirectories,
    };

    const service = init({ typescript: ts }).create({
        languageService: ts.createLanguageService(host),
        languageServiceHost: host,
        serverHost: ts.sys,
        config: {},
    } as unknown as ts.server.PluginCreateInfo);

    return service.getSuggestionDiagnostics(client);
};

describe('a generated client that has fallen behind', () => {
    it('is reported when a file its contract imports is newer', () => {
        const { directory, client, contract } = project({ routesNewer: true });
        const stale = diagnosticsFor(directory, client, contract).find((diagnostic) => diagnostic.code === STALE_CLIENT_CODE);

        expect(stale).toBeDefined();
        expect(stale?.messageText).toContain('routes.ts');
        expect(stale?.messageText).toContain('pnpm kizuna generate');
        expect(stale?.start).toBe(0);
    });

    it('is quiet when the client is newer than everything it came from', () => {
        const { directory, client, contract } = project({ routesNewer: false });

        expect(diagnosticsFor(directory, client, contract).some((diagnostic) => diagnostic.code === STALE_CLIENT_CODE)).toBe(false);
    });
});
