/**
 * This file was automatically generated by ts-kizuna.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source kizuna config,
 * and re-run `kizuna generate` to regenerate this file.
 */
import type { honoAdapter } from '@ts-kizuna/hono';
import type { mcpPlugin } from '@ts-kizuna/mcp';
import type { openApiPlugin } from '@ts-kizuna/openapi';
import type { GuardSchema, analytics, jobs, tags, tools, user, member, inviteToken, scheduler } from '@ts-kizuna-demo/shared';

export interface Config {
    adapter: typeof honoAdapter;
    tags: typeof tags;
    identities: {
        user: typeof user;
        member: typeof member;
        inviteToken: typeof inviteToken;
        scheduler: typeof scheduler;
    };
    requestContext: {
        analytics: typeof analytics;
    };
    guardSchema: typeof GuardSchema;
    issueCodes: 'invalid_phone_number';
    jobs: typeof jobs;
    tools: typeof tools;
    plugins: [ReturnType<typeof mcpPlugin>, ReturnType<typeof openApiPlugin>];
}
