/**
 * This file was automatically generated by kizuna.
 * DO NOT MODIFY IT BY HAND. Instead, add or move a `content.ts` under `app/`,
 * and re-run `kizuna generate` to regenerate this file.
 */
import contactPage from './app/contact/content';
import springPage from './app/lp/spring/content';

export const pages = {
    contactPage: {
        path: '/contact',
        page: contactPage,
    },
    springPage: {
        path: '/lp/spring',
        page: springPage,
    },
};
