/**
 * This file was automatically generated by kizuna.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source kizuna config,
 * and re-run `kizuna generate` to regenerate this file.
 */
import type { GuardSchema, analytics, groups, jobs, user, member, inviteToken, scheduler } from '@kizunajs-demo/shared';

export interface Config {
    groups: typeof groups;
    auth: {
        identities: {
            user: typeof user;
            member: typeof member;
            inviteToken: typeof inviteToken;
            scheduler: typeof scheduler;
        };
        guardSchema: typeof GuardSchema;
    };
    requestContext: {
        analytics: typeof analytics;
    };
    validation: {
        issueCodes: 'invalid_phone_number';
    };
    jobs: typeof jobs;
}
