/**
 * This file was automatically generated by kizuna.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source kizuna config,
 * and re-run `kizuna generate` to regenerate this file.
 */
import type { GuardSchema } from './guard-schema';
import type { user, member, inviteToken, scheduler } from './identities';
import type { jobs } from './jobs';
import type { analytics } from './request-context';
import type { tags } from './tags';

export interface Config {
    tags: typeof tags;
    auth: {
        identities: {
            user: typeof user;
            member: typeof member;
            inviteToken: typeof inviteToken;
            scheduler: typeof scheduler;
        };
        guardSchema: typeof GuardSchema;
    };
    requestContext: {
        analytics: typeof analytics;
    };
    validation: {
        issueCodes: 'invalid_phone_number';
    };
    jobs: typeof jobs;
}
