/**
 * This file was automatically generated by kizuna.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source kizuna config,
 * and re-run `kizuna generate` to regenerate this file.
 */
import type { nextAdapter } from '@kizunajs/next';
import type { mcpPlugin } from '@kizunajs/mcp';
import type { openApiPlugin } from '@kizunajs/openapi';
import type { cmsPlugin } from '@kizunajs/cms';
import type { GuardSchema, analytics, jobs, tags, user, member, inviteToken, scheduler } from '@kizunajs-demo/shared';
import type { editor, site } from './src/cms/identities';

export interface Config {
    adapter: ReturnType<typeof nextAdapter>;
    tags: typeof tags;
    auth: {
        identities: {
            user: typeof user;
            member: typeof member;
            inviteToken: typeof inviteToken;
            scheduler: typeof scheduler;
            editor: typeof editor;
            site: typeof site;
        };
        guardSchema: typeof GuardSchema;
    };
    requestContext: {
        analytics: typeof analytics;
    };
    validation: {
        issueCodes: 'invalid_phone_number';
    };
    jobs: typeof jobs;
    plugins: [ReturnType<typeof mcpPlugin>, ReturnType<typeof openApiPlugin>, ReturnType<typeof cmsPlugin>];
}
