/* eslint-disable */
/**
 * Generated by @kizunajs/fetch. Do not edit.
 *
 * Regenerate: kizuna generate
 */
import { createGeneratedClient, type $brand, type ClientConfig, type ClientMethod, type GeneratedRoutes } from './client.js';

export namespace API {
    export type Center = {
        id: CenterId;
        name: string;
        parentId: CenterId | null;
    };

    /**
     * A branded `string`. Responses hand one back, and `toCenterId` makes one from a plain value.
     */
    export type CenterId = string & $brand<"CenterId">;

    /**
     * RFC 9457 Problem Details error response for validation failures.
     */
    export type ValidationError = {
        type: string;
        title: string;
        status: number;
        detail: string;
        errors: Array<{
            code: "invalid_type" | "too_small" | "too_big" | "invalid_string_format" | "not_multiple_of" | "unrecognized_keys" | "invalid_union" | "invalid_key" | "invalid_element" | "invalid_value" | "custom" | string;
            path: Array<string>;
            message: string;
        }>;
    };

    export namespace CentersGetCenter {
        export type Params = {
            centerId: CenterId;
        };

        export type Result =
            | { status: 200; body: Center; headers: Record<string, string> };
    }

    export namespace CentersListCenters {
        export type Query = {
            parentId?: CenterId;
        };

        export type Result =
            | { status: 200; body: Array<Center>; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace CentersMoveCenter {
        export type Params = {
            centerId: CenterId;
        };

        export type Body = {
            parentId: CenterId;
        };

        export type Headers = {
            "x-actor-center": CenterId;
        };

        export type Result =
            | { status: 200; body: Center; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }
}

export interface Client {
    centers: {
        /**
         * @example
         * const result = await client.centers.getCenter({
         *     params: {
         *         centerId: '1',
         *     },
         * });
         */
        getCenter: ClientMethod<'GET', false, {
            params: API.CentersGetCenter.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.CentersGetCenter.Result>;
        /**
         * @example
         * const result = await client.centers.listCenters();
         */
        listCenters: ClientMethod<'GET', false, {
            query?: API.CentersListCenters.Query;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.CentersListCenters.Result>;
        /**
         * @example
         * const result = await client.centers.moveCenter({
         *     params: {
         *         centerId: '1',
         *     },
         *     body: {
         *         parentId: '1',
         *     },
         * });
         */
        moveCenter: ClientMethod<'POST', false, {
            params: API.CentersMoveCenter.Params;
            body: API.CentersMoveCenter.Body;
            headers?: API.CentersMoveCenter.Headers;
            fetchOptions?: RequestInit;
        }, API.CentersMoveCenter.Result>;
    };
}

const routes: GeneratedRoutes = {
    centers: {
        getCenter: {
            method: 'GET',
            path: '/centers/:centerId',
            responses: {
                200: {},
            },
        },
        listCenters: {
            method: 'GET',
            path: '/centers',
            responses: {
                200: {},
            },
        },
        moveCenter: {
            method: 'POST',
            path: '/centers/:centerId/move',
            responses: {
                200: {},
            },
        },
    },
};

/**
 * Brands a value from outside the API, like a URL segment, as `API.CenterId`. A value from a response is branded already.
 *
 * @example
 * const id = toCenterId('1');
 */
export const toCenterId = (value: string): API.CenterId => value as API.CenterId;

/**
 * A client for this API. Pass the base URL and anything else the runtime takes.
 */
export const createClient = (config: ClientConfig): Client => createGeneratedClient(routes, config) as unknown as Client;
