/* eslint-disable */
/**
 * Generated by @kizunajs/fetch. Do not edit.
 *
 * Regenerate: kizuna generate
 */
import { createGeneratedClient, type $brand, type ClientConfig, type ClientMethod, type GeneratedRoutes } from './client.js';

export namespace API {
    export type Center = {
        id: CenterId;
        name: string;
        parentId: CenterId | null;
    };

    /**
     * A branded `string`.
     *
     * Brand a plain value with `API.CenterId.parse`.
     */
    export type CenterId = string & $brand<"CenterId">;

    /**
     * A validated, branded `string`.
     *
     * Validate a plain value with `API.InviteCode.isValid`, and brand it with `API.InviteCode.parse`.
     */
    export type InviteCode = string & $brand<"InviteCode">;

    /**
     * A validated, branded `number`.
     *
     * Validate a plain value with `API.Seats.isValid`, and brand it with `API.Seats.parse`.
     */
    export type Seats = number & $brand<"Seats">;

    /**
     * RFC 9457 Problem Details error response for validation failures.
     */
    export type ValidationError = {
        type: string;
        title: string;
        status: number;
        detail: string;
        errors: Array<{
            code: "invalid_type" | "too_small" | "too_big" | "invalid_string_format" | "not_multiple_of" | "unrecognized_keys" | "invalid_union" | "invalid_key" | "invalid_element" | "invalid_value" | "custom" | string;
            path: Array<string>;
            message: string;
        }>;
    };

    export namespace CentersGetCenter {
        export type Params = {
            centerId: CenterId;
        };

        export type Result =
            | { status: 200; body: Center; headers: Record<string, string> };
    }

    export namespace CentersListCenters {
        export type Query = {
            parentId?: CenterId;
        };

        export type Result =
            | { status: 200; body: Array<Center>; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace CentersRedeemInvite {
        export type Params = {
            /**
             * @example
             * 'inv_k7f3q9'
             */
            code: InviteCode;
        };

        export type Body = {
            seats: Seats;
        };

        export type Result =
            | { status: 204; body: undefined; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace CentersMoveCenter {
        export type Params = {
            centerId: CenterId;
        };

        export type Body = {
            parentId: CenterId;
        };

        export type Headers = {
            "x-actor-center": CenterId;
        };

        export type Result =
            | { status: 200; body: Center; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }
}

export interface Client {
    centers: {
        /**
         * @example
         * const result = await client.centers.getCenter({
         *     params: {
         *         centerId: '1',
         *     },
         * });
         */
        getCenter: ClientMethod<'GET', false, {
            params: API.CentersGetCenter.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.CentersGetCenter.Result>;
        /**
         * @example
         * const result = await client.centers.listCenters();
         */
        listCenters: ClientMethod<'GET', false, {
            query?: API.CentersListCenters.Query;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.CentersListCenters.Result>;
        /**
         * @example
         * const result = await client.centers.redeemInvite({
         *     params: {
         *         code: 'inv_k7f3q9',
         *     },
         *     body: {
         *         seats: 1,
         *     },
         * });
         */
        redeemInvite: ClientMethod<'POST', false, {
            params: API.CentersRedeemInvite.Params;
            body: API.CentersRedeemInvite.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.CentersRedeemInvite.Result>;
        /**
         * @example
         * const result = await client.centers.moveCenter({
         *     params: {
         *         centerId: '1',
         *     },
         *     body: {
         *         parentId: '1',
         *     },
         * });
         */
        moveCenter: ClientMethod<'POST', false, {
            params: API.CentersMoveCenter.Params;
            body: API.CentersMoveCenter.Body;
            headers?: API.CentersMoveCenter.Headers;
            fetchOptions?: RequestInit;
        }, API.CentersMoveCenter.Result>;
    };
}

const routes: GeneratedRoutes = {
    centers: {
        getCenter: {
            method: 'GET',
            path: '/centers/:centerId',
            responses: {
                200: {},
            },
        },
        listCenters: {
            method: 'GET',
            path: '/centers',
            responses: {
                200: {},
            },
        },
        redeemInvite: {
            method: 'POST',
            path: '/invites/:code/redeem',
            responses: {
                204: {},
            },
        },
        moveCenter: {
            method: 'POST',
            path: '/centers/:centerId/move',
            responses: {
                200: {},
            },
        },
    },
};

/**
 * Brands plain values.
 *
 * A value from a response is branded already, so these are for one from outside the API, like a URL segment.
 */
export const API = {
    CenterId: {
        /**
         * Brands a plain value as `API.CenterId`.
         *
         * For a value from outside the API, like a URL segment. One from a response is branded already.
         *
         * @example
         * const centerId = API.CenterId.parse('1');
         */
        parse: (value: string): API.CenterId => value as API.CenterId,
    },

    InviteCode: {
        /**
         * Validates a plain value.
         *
         * Narrows it to `API.InviteCode` when it passes.
         *
         * @example
         * if (API.InviteCode.isValid(value)) {
         *     const inviteCode: API.InviteCode = value;
         * }
         */
        isValid: (value: string): value is API.InviteCode => /^inv_[a-z0-9]+$/i.test(value) && value.length <= 20,

        /**
         * Brands a plain value as `API.InviteCode`.
         *
         * Throws a `TypeError` when it fails validation.
         *
         * @example
         * const inviteCode = API.InviteCode.parse('inv_k7f3q9');
         */
        parse: (value: string): API.InviteCode => {
            if (!API.InviteCode.isValid(value)) throw new TypeError('Not a valid InviteCode: ' + value);
            return value;
        },
    },

    Seats: {
        /**
         * Validates a plain value.
         *
         * Narrows it to `API.Seats` when it passes.
         *
         * @example
         * if (API.Seats.isValid(value)) {
         *     const seats: API.Seats = value;
         * }
         */
        isValid: (value: number): value is API.Seats => Number.isInteger(value) && value >= 1 && value <= 500,

        /**
         * Brands a plain value as `API.Seats`.
         *
         * Throws a `TypeError` when it fails validation.
         *
         * @example
         * const seats = API.Seats.parse(value);
         */
        parse: (value: number): API.Seats => {
            if (!API.Seats.isValid(value)) throw new TypeError('Not a valid Seats: ' + value);
            return value;
        },
    },
};

/**
 * A client for this API. Pass the base URL and anything else the runtime takes.
 */
export const createClient = (config: ClientConfig): Client => createGeneratedClient(routes, config) as unknown as Client;
