/* eslint-disable */
/**
 * Generated by @ts-kizuna/fetch. Do not edit.
 *
 * Regenerate: kizuna generate
 */
import { createGeneratedClient, type ClientConfig, type GeneratedRoutes } from '@ts-kizuna/fetch';

export namespace API {
    export type CreateUserInput = {
        /** Display name */
        name: string;
        /** Email address */
        email: string;
        /** Family name. Snake_case wire key, kept verbatim by both clients. */
        last_name?: string;
        /** Phone number in E.164-ish form. Demonstrates a custom-coded validation issue. */
        phone?: string;
    };

    export type EmailEvent = {
        channel: "email";
        to: string;
        subject: string;
    };

    export type EventRecord = {
        id: string;
        kind: "login" | "logout" | "signup";
        occurredAt: string;
        userId: string;
    };

    export type GuardDenial = {
        type: string;
        title: string;
        status: number;
        detail: string;
        code?: "unauthenticated" | "expired_token" | "forbidden" | "not_found";
    };

    /**
     * RFC 9457 Problem Details error response.
     */
    export type ProblemDetails = {
        type: string;
        title: string;
        status: number;
        detail: string;
    };

    export type SmsEvent = {
        channel: "sms";
        phone: string;
        text: string;
    };

    /**
     * A user in the system
     */
    export type User = {
        /** Unique user identifier */
        id: string;
        /** Display name */
        name: string;
        /** Email address */
        email: string;
        /** Email address */
        email_address?: string;
        /** Family name on the wire as `last_name`, exercises snake_case fidelity through the generators. */
        last_name?: string;
        /** Sibling anonymous objects (`avatar` / `avatars`) exercise inline-object naming where one field name is a prefix of another. */
        avatar?: {
            id: string;
            url: string;
        };
        avatars?: Array<{
            id: string;
            url: string;
        }>;
    };

    export namespace UsersListUsers {
        export type Query = {
            /** Page number, starting at 1 */
            page?: number;
            /** Page size (1–100) */
            limit?: number;
        };

        export type Result =
            | { status: 200; body: {
                users: Array<User>;
                total: number;
            }; headers: Record<string, string> };
    }

    export namespace UsersExportUsers {
        export type Result =
            | { status: 200; body: string; headers: Record<string, string> };
    }

    export namespace UsersUserBadge {
        export type Params = {
            id: string;
        };

        export type Result =
            | { status: 200; body: Uint8Array; headers: Record<string, string> }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace UsersLastSessionEvent {
        export type Params = {
            id: string;
        };

        export type Result =
            | { status: 200; body: {
                kind: "login";
                at: string;
                ipAddress: string;
                userAgent: string;
            } | {
                kind: "logout";
                at: string;
                reason: "signed_out" | "session_expired";
            }; headers: Record<string, string> }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace UsersSearchUsers {
        export type Query = {
            q: string;
            limit: number;
            cursor: number;
        };

        export type Result =
            | { status: 200; body: {
                users: Array<User>;
                nextCursor?: number | null;
            }; headers: Record<string, string> };
    }

    export namespace UsersGetUser {
        export type Params = {
            id: string;
        };

        export type Headers = {
            "x-request-id": string;
        };

        export type Result =
            | { status: 200; body: User; headers: {
                "x-request-id"?: string;
            } }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace UsersUserActivity {
        export type Params = {
            id: string;
            year: number;
        };

        export type Result =
            | { status: 200; body: {
                userId: string;
                year: number;
                events: number;
            }; headers: Record<string, string> }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace UsersUserProfile {
        export type Params = {
            id: string;
        };

        export type Result =
            | { status: 200; body: User; headers: Record<string, string> }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace UsersCreateUser {
        export type Body = CreateUserInput;

        export type Result =
            | { status: 201; body: User; headers: Record<string, string> }
            | { status: 400; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace UsersDeleteUser {
        export type Params = {
            id: string;
        };

        export type Result =
            | { status: 200; body: {
                success: boolean;
            }; headers: Record<string, string> }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace UsersArchiveUser {
        export type Params = {
            id: string;
        };

        export type Result =
            | { status: 200; body: {
                alreadyArchived: "true";
                userId: string;
            }; headers: Record<string, string> }
            | { status: 201; body: {
                archivedAt: string;
                userId: string;
            }; headers: Record<string, string> };
    }

    export namespace UsersUploadAvatar {
        export type Body = {
            file: File | Blob;
            userId: string;
        };

        export type Result =
            | { status: 200; body: {
                size: number;
                userId: string;
            }; headers: Record<string, string> };
    }

    export namespace UsersPingUser {
        export type Params = {
            id: string;
        };

        export type Body = undefined;

        export type Result =
            | { status: 204; body: undefined; headers: Record<string, string> };
    }

    export namespace UsersGetMyWork {
        export type Result =
            | { status: 200; body: {
                items: Array<string>;
                contentType: "image/jpeg" | "text-plain" | "video.mp4" | "3d-model";
            }; headers: Record<string, string> }
            | { status: 204; body: undefined; headers: Record<string, string> };
    }

    export namespace UsersCheckUser {
        export type Params = {
            id: string;
        };

        export type Result =
            | { status: 200; body: {
                exists: boolean;
            }; headers: Record<string, string> }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace UsersDescribeUsers {
        export type Result =
            | { status: 200; body: {
                allow: string;
            }; headers: Record<string, string> };
    }

    export namespace HealthCheck {
        export type Result =
            | { status: 200; body: {
                ok: boolean;
            }; headers: Record<string, string> };
    }

    export namespace HealthVersion {
        export type Result =
            | { status: 200; body: {
                version: string;
            }; headers: Record<string, string> };
    }

    export namespace HealthHistory {
        export type Result =
            | { status: 200; body: Array<{
                ok: boolean;
                checkedAt: string;
            }>; headers: Record<string, string> };
    }

    export namespace NotificationsSendNotification {
        export type Body = EmailEvent | SmsEvent;

        export type Result =
            | { status: 202; body: {
                accepted: boolean;
            }; headers: Record<string, string> };
    }

    export namespace NotificationsListEvents {
        export type Query = {
            /** Lower bound for occurredAt, wire format is ISO-8601 */
            since?: string;
            kind?: "login" | "logout" | "signup";
            /** Filter by id; repeated query param */
            ids?: Array<string>;
            /** Arbitrary label, exercises z.string().transform() */
            label?: unknown;
            /** One or many tag IDs, exercises non-discriminated union codegen */
            tagIds?: Array<string> | unknown;
        };

        export type Result =
            | { status: 200; body: {
                events: Array<EventRecord>;
                echo: {
                    since?: string | null;
                    kind?: "login" | "logout" | "signup" | null;
                    ids?: Array<string> | null;
                    label?: string | null;
                    tagIds?: Array<string> | null;
                    sessionId?: string | null;
                };
            }; headers: Record<string, string> };
    }

    export namespace NotificationsValidateConfig {
        export type Body = {
            default: string;
            interval: number;
        };

        export type Result =
            | { status: 200; body: {
                status: string;
            }; headers: Record<string, string> }
            | { status: 400; body: ProblemDetails; headers: Record<string, string> }
            | { status: 401; body: undefined; headers: Record<string, string> };
    }

    export namespace NotificationsWebhook {
        export type Body = unknown;

        export type Result =
            | { status: 200; body: {
                received: boolean;
            }; headers: Record<string, string> };
    }

    export namespace MembersListMembers {
        export type Result =
            | { status: 200; body: {
                members: Array<User>;
            }; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: {
                "www-authenticate": string;
            } }
            | { status: 403; body: GuardDenial; headers: Record<string, string> };
    }

    export namespace MembersInviteMember {
        export type Body = {
            email: string;
        };

        export type Result =
            | { status: 201; body: User; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: {
                "www-authenticate"?: string;
            } }
            | { status: 403; body: GuardDenial; headers: Record<string, string> }
            | { status: 409; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace MembersCancelInvite {
        export type Params = {
            inviteId: string;
        };

        export type Result =
            | { status: 200; body: {
                cancelled: boolean;
            }; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: {
                "www-authenticate"?: string;
            } }
            | { status: 403; body: GuardDenial; headers: Record<string, string> }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace WorkspaceGetWorkspace {
        export type Result =
            | { status: 200; body: {
                id: string;
                name: string;
            }; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: Record<string, string> }
            | { status: 403; body: GuardDenial; headers: Record<string, string> };
    }

    export namespace WorkspaceDeleteWorkspace {
        export type Result =
            | { status: 200; body: {
                ok: boolean;
            }; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: Record<string, string> }
            | { status: 403; body: GuardDenial; headers: Record<string, string> };
    }

    export namespace WorkspaceTransfer {
        export type Body = {
            toUserId: string;
        };

        export type Result =
            | { status: 200; body: {
                ok: boolean;
            }; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: Record<string, string> }
            | { status: 403; body: GuardDenial; headers: Record<string, string> };
    }

    export namespace InvitesGetInvite {
        export type Params = {
            token: string;
        };

        export type Result =
            | { status: 200; body: {
                inviteId: string;
                email: string;
            }; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: Record<string, string> }
            | { status: 403; body: GuardDenial; headers: Record<string, string> }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace InvitesAcceptInvite {
        export type Params = {
            token: string;
        };

        export type Body = {
            name: string;
        };

        export type Result =
            | { status: 201; body: {
                userId: string;
            }; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: Record<string, string> }
            | { status: 403; body: GuardDenial; headers: Record<string, string> }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace AssistantReply {
        export type Body = {
            prompt: string;
        };

        export type Result =
            | { status: 200; body: AsyncIterable<{ event: 'delta'; data: {
                text: string;
            }; id?: string; retry?: number } | { event: 'done'; data: {
                inputTokens: number;
                outputTokens: number;
            }; id?: string; retry?: number } | { event: 'tool_call'; data: {
                id: string;
                name: "getForecast";
                input: {
                    params: {
                        city: string;
                    };
                    query: {
                        unit?: "celsius" | "fahrenheit";
                    };
                };
            } | {
                id: string;
                name: "plotSignups";
                input: {
                    query: {
                        days: number;
                    };
                };
            } | {
                id: string;
                name: "countWords";
                input: {
                    body: {
                        text: string;
                    };
                };
            }; id?: string; retry?: number } | { event: 'tool_result'; data: {
                id: string;
                name: "getForecast";
                output: {
                    temperature: number;
                    unit: "celsius" | "fahrenheit";
                    summary: string;
                };
            } | {
                id: string;
                name: "plotSignups";
                output: {
                    points: Array<{
                        date: string;
                        signups: number;
                    }>;
                };
            } | {
                id: string;
                name: "countWords";
                output: {
                    words: number;
                };
            }; id?: string; retry?: number } | { event: 'tool_error'; data: {
                id: string;
                name: "getForecast" | "plotSignups" | "countWords";
                message: string;
            }; id?: string; retry?: number }>; headers: Record<string, string> }
            | { status: 400; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace ToolsGetForecast {
        export type Params = {
            city: string;
        };

        export type Query = {
            unit?: "celsius" | "fahrenheit";
        };

        export type Result =
            | { status: 200; body: {
                temperature: number;
                unit: "celsius" | "fahrenheit";
                summary: string;
            }; headers: Record<string, string> };
    }

    export namespace ToolsPlotSignups {
        export type Query = {
            days: number;
        };

        export type Result =
            | { status: 200; body: {
                points: Array<{
                    date: string;
                    signups: number;
                }>;
            }; headers: Record<string, string> };
    }

    export namespace ToolsCountWords {
        export type Body = {
            text: string;
        };

        export type Result =
            | { status: 200; body: {
                words: number;
            }; headers: Record<string, string> };
    }

    export namespace DiagnosticsWhoAmI {
        export type Result =
            | { status: 200; body: {
                path: string;
                method: string;
                userAgent?: string | null;
            }; headers: Record<string, string> };
    }
}

export interface Client {
    users: {
        listUsers(args?: {
            query?: API.UsersListUsers.Query;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.UsersListUsers.Result>;
        exportUsers(args?: {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.UsersExportUsers.Result>;
        userBadge(args: {
            params: API.UsersUserBadge.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.UsersUserBadge.Result>;
        lastSessionEvent(args: {
            params: API.UsersLastSessionEvent.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.UsersLastSessionEvent.Result>;
        searchUsers(args?: {
            query?: API.UsersSearchUsers.Query;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.UsersSearchUsers.Result>;
        getUser(args: {
            params: API.UsersGetUser.Params;
            headers?: API.UsersGetUser.Headers;
            fetchOptions?: RequestInit;
        }): Promise<API.UsersGetUser.Result>;
        userActivity(args: {
            params: API.UsersUserActivity.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.UsersUserActivity.Result>;
        userProfile(args: {
            params: API.UsersUserProfile.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.UsersUserProfile.Result>;
        createUser(args: {
            body: API.UsersCreateUser.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.UsersCreateUser.Result>;
        deleteUser(args: {
            params: API.UsersDeleteUser.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.UsersDeleteUser.Result>;
        archiveUser(args: {
            params: API.UsersArchiveUser.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.UsersArchiveUser.Result>;
        uploadAvatar(args: {
            body: API.UsersUploadAvatar.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.UsersUploadAvatar.Result>;
        pingUser(args: {
            params: API.UsersPingUser.Params;
            body: API.UsersPingUser.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.UsersPingUser.Result>;
        getMyWork(args?: {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.UsersGetMyWork.Result>;
        checkUser(args: {
            params: API.UsersCheckUser.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.UsersCheckUser.Result>;
        describeUsers(args?: {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.UsersDescribeUsers.Result>;
    };
    health: {
        check(args?: {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.HealthCheck.Result>;
        version(args?: {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.HealthVersion.Result>;
        history(args?: {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.HealthHistory.Result>;
    };
    notifications: {
        sendNotification(args: {
            body: API.NotificationsSendNotification.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.NotificationsSendNotification.Result>;
        listEvents(args?: {
            query?: API.NotificationsListEvents.Query;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.NotificationsListEvents.Result>;
        validateConfig(args: {
            body: API.NotificationsValidateConfig.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.NotificationsValidateConfig.Result>;
        webhook(args: {
            body: API.NotificationsWebhook.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.NotificationsWebhook.Result>;
    };
    members: {
        listMembers(args?: {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.MembersListMembers.Result>;
        inviteMember(args: {
            body: API.MembersInviteMember.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.MembersInviteMember.Result>;
        cancelInvite(args: {
            params: API.MembersCancelInvite.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.MembersCancelInvite.Result>;
    };
    workspace: {
        getWorkspace(args?: {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.WorkspaceGetWorkspace.Result>;
        deleteWorkspace(args?: {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.WorkspaceDeleteWorkspace.Result>;
        transfer(args: {
            body: API.WorkspaceTransfer.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.WorkspaceTransfer.Result>;
    };
    invites: {
        getInvite(args: {
            params: API.InvitesGetInvite.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.InvitesGetInvite.Result>;
        acceptInvite(args: {
            params: API.InvitesAcceptInvite.Params;
            body: API.InvitesAcceptInvite.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.InvitesAcceptInvite.Result>;
    };
    assistant: {
        reply(args: {
            body: API.AssistantReply.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.AssistantReply.Result>;
    };
    tools: {
        getForecast(args: {
            params: API.ToolsGetForecast.Params;
            query?: API.ToolsGetForecast.Query;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.ToolsGetForecast.Result>;
        plotSignups(args?: {
            query?: API.ToolsPlotSignups.Query;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.ToolsPlotSignups.Result>;
        countWords(args: {
            body: API.ToolsCountWords.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.ToolsCountWords.Result>;
    };
    diagnostics: {
        whoAmI(args?: {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }): Promise<API.DiagnosticsWhoAmI.Result>;
    };
}

const routes: GeneratedRoutes = {
    users: {
        listUsers: {
            method: 'GET',
            path: '/users',
            responses: {
                200: {},
            },
        },
        exportUsers: {
            method: 'GET',
            path: '/users/export',
            responses: {
                200: {},
            },
        },
        userBadge: {
            method: 'GET',
            path: '/users/:id/badge',
            responses: {
                200: {},
                404: {},
            },
        },
        lastSessionEvent: {
            method: 'GET',
            path: '/users/:id/last-session-event',
            responses: {
                200: {},
                404: {},
            },
        },
        searchUsers: {
            method: 'GET',
            path: '/users/search',
            responses: {
                200: {},
            },
        },
        getUser: {
            method: 'GET',
            path: '/users/:id',
            responses: {
                200: {},
                404: {},
            },
        },
        userActivity: {
            method: 'GET',
            path: '/users/:id/activity/:year',
            responses: {
                200: {},
                404: {},
            },
        },
        userProfile: {
            method: 'GET',
            path: '/users/:id/profile',
            responses: {
                200: {},
                404: {},
            },
        },
        createUser: {
            method: 'POST',
            path: '/users',
            responses: {
                201: {},
                400: {},
            },
        },
        deleteUser: {
            method: 'DELETE',
            path: '/users/:id',
            responses: {
                200: {},
                404: {},
            },
        },
        archiveUser: {
            method: 'POST',
            path: '/users/:id/archive',
            responses: {
                200: {},
                201: {},
            },
        },
        uploadAvatar: {
            method: 'POST',
            path: '/avatar',
            contentType: 'multipart/form-data',
            responses: {
                200: {},
            },
        },
        pingUser: {
            method: 'POST',
            path: '/users/:id/ping',
            responses: {
                204: {},
            },
        },
        getMyWork: {
            method: 'GET',
            path: '/work',
            responses: {
                200: {},
                204: {},
            },
        },
        checkUser: {
            method: 'HEAD',
            path: '/users/:id/check',
            responses: {
                200: {},
                404: {},
            },
        },
        describeUsers: {
            method: 'OPTIONS',
            path: '/users/describe',
            responses: {
                200: {},
            },
        },
    },
    health: {
        check: {
            method: 'GET',
            path: '/health',
            responses: {
                200: {},
            },
        },
        version: {
            method: 'GET',
            path: '/health/version',
            responses: {
                200: {},
            },
        },
        history: {
            method: 'GET',
            path: '/health/history',
            responses: {
                200: {},
            },
        },
    },
    notifications: {
        sendNotification: {
            method: 'POST',
            path: '/notifications',
            responses: {
                202: {},
            },
        },
        listEvents: {
            method: 'GET',
            path: '/events',
            responses: {
                200: {},
            },
        },
        validateConfig: {
            method: 'POST',
            path: '/schemas/validate',
            responses: {
                200: {},
                400: {},
                401: {},
            },
        },
        webhook: {
            method: 'POST',
            path: '/webhook',
            responses: {
                200: {},
            },
        },
    },
    members: {
        listMembers: {
            method: 'GET',
            path: '/workspace/members',
            responses: {
                200: {},
                401: {},
                403: {},
            },
        },
        inviteMember: {
            method: 'POST',
            path: '/workspace/members',
            responses: {
                201: {},
                401: {},
                403: {},
                409: {},
            },
        },
        cancelInvite: {
            method: 'DELETE',
            path: '/workspace/invites/:inviteId',
            responses: {
                200: {},
                401: {},
                403: {},
                404: {},
            },
        },
    },
    workspace: {
        getWorkspace: {
            method: 'GET',
            path: '/workspace',
            responses: {
                200: {},
                401: {},
                403: {},
            },
        },
        deleteWorkspace: {
            method: 'DELETE',
            path: '/workspace',
            responses: {
                200: {},
                401: {},
                403: {},
            },
        },
        transfer: {
            method: 'POST',
            path: '/workspace/transfer',
            responses: {
                200: {},
                401: {},
                403: {},
            },
        },
    },
    invites: {
        getInvite: {
            method: 'GET',
            path: '/invites/:token',
            responses: {
                200: {},
                401: {},
                403: {},
                404: {},
            },
        },
        acceptInvite: {
            method: 'POST',
            path: '/invites/:token/accept',
            responses: {
                201: {},
                401: {},
                403: {},
                404: {},
            },
        },
    },
    assistant: {
        reply: {
            method: 'POST',
            path: '/assistant/reply',
            responses: {
                200: { stream: { contentType: 'text/event-stream' } },
                400: {},
            },
        },
    },
    tools: {
        getForecast: {
            method: 'GET',
            path: '/forecast/:city',
            responses: {
                200: {},
            },
        },
        plotSignups: {
            method: 'GET',
            path: '/signups',
            responses: {
                200: {},
            },
        },
        countWords: {
            method: 'POST',
            path: '/text/word-count',
            responses: {
                200: {},
            },
        },
    },
    diagnostics: {
        whoAmI: {
            method: 'GET',
            path: '/diagnostics/caller',
            responses: {
                200: {},
            },
        },
    },
};

export interface RequestContext {
    "x-posthog-session-id"?: string;
    "x-posthog-distinct-id"?: string;
}

/**
 * A client for this API. Pass the base URL, the request context headers this
 * API declares, and anything else the runtime takes.
 */
export const createClient = (config: ClientConfig & { requestContext?: RequestContext }): Client =>
    createGeneratedClient(routes, config) as unknown as Client;
