/* eslint-disable */
/**
 * Generated by @kizunajs/fetch. Do not edit.
 *
 * Regenerate: kizuna generate
 */
/**
 * Tells one branded type from another with the same base. The server declares
 * the same shape, so an id it hands out is the type this client takes.
 */
type KizunaBrand<Name extends string> = {
    readonly '~kizunaBrand': {
        readonly [Key in Name]: true;
    };
};

export namespace API {
    export type CreateUserInput = {
        /**
         * Display name
         *
         * @example
         * 'Alice Johnson'
         */
        name: string;
        /**
         * Email address
         *
         * @example
         * 'alice@example.com'
         */
        email: string;
        /**
         * Family name. Snake_case wire key, kept verbatim by both clients.
         *
         * @example
         * 'Hopper'
         */
        last_name?: string;
        /**
         * Phone number in E.164-ish form. Demonstrates a custom-coded validation issue.
         *
         * @example
         * '+15551234567'
         */
        phone?: string;
    };

    export type EmailEvent = {
        channel: "email";
        to: string;
        subject: string;
    };

    export type EventKind = "login" | "logout" | "signup";

    export type EventRecord = {
        id: string;
        kind: EventKind;
        occurredAt: string;
        userId: string;
    };

    export type GuardDenial = {
        type: string;
        title: string;
        status: number;
        detail: string;
        code?: "unauthenticated" | "expired_token" | "forbidden" | "not_found";
    };

    export type NotificationEvent = EmailEvent | SmsEvent;

    /**
     * RFC 9457 Problem Details error response.
     */
    export type ProblemDetails = {
        type: string;
        title: string;
        status: number;
        detail: string;
    };

    export type Product = {
        id: ProductId;
        name: string;
        price: number;
        imageUrl: string;
    };

    /**
     * A branded `string`. Responses hand one back, and `toProductId` makes one from a plain value.
     */
    export type ProductId = string & KizunaBrand<"ProductId">;

    export type SmsEvent = {
        channel: "sms";
        phone: string;
        text: string;
    };

    /**
     * A user in the system
     */
    export type User = {
        /**
         * Unique user identifier
         *
         * @example
         * 'usr_abc123'
         */
        id: UserId;
        /**
         * Display name
         *
         * @example
         * 'Alice Johnson'
         */
        name: string;
        /**
         * Email address
         *
         * @deprecated use `email_address` instead.
         *
         * @example
         * 'alice@example.com'
         */
        email: string;
        /**
         * Email address
         *
         * @example
         * 'alice@example.com'
         */
        email_address?: string;
        /**
         * Family name on the wire as `last_name`, exercises snake_case fidelity through the generators.
         *
         * @example
         * 'Hopper'
         */
        last_name?: string;
        /**
         * Sibling anonymous objects (`avatar` / `avatars`) exercise inline-object naming where one field name is a prefix of another.
         */
        avatar?: {
            id: string;
            url: string;
        } | null;
        avatars?: Array<{
            id: string;
            url: string;
        }>;
        /**
         * Free-form string map, exercises a record through the generators.
         */
        metadata?: Record<string, string>;
        /**
         * Entries may be null, exercises a nullable array element, which `optional` cannot express.
         */
        tags?: Array<string | null>;
    };

    /**
     * A branded `string`. Responses hand one back, and `toUserId` makes one from a plain value.
     */
    export type UserId = string & KizunaBrand<"UserId">;

    export type UserSessionEvent = {
        kind: "login";
        at: string;
        ipAddress: string;
        userAgent: string;
    } | {
        kind: "logout";
        at: string;
        reason: "signed_out" | "session_expired";
    };

    /**
     * RFC 9457 Problem Details error response for validation failures.
     */
    export type ValidationError = {
        type: string;
        title: string;
        status: number;
        detail: string;
        errors: Array<{
            code: "invalid_type" | "too_small" | "too_big" | "invalid_string_format" | "not_multiple_of" | "unrecognized_keys" | "invalid_union" | "invalid_key" | "invalid_element" | "invalid_value" | "custom" | string;
            path: Array<string>;
            message: string;
        }>;
    };

    export namespace UsersListUsers {
        export type Query = {
            /**
             * Page number, starting at 1
             *
             * @example
             * 1
             */
            page?: number;
            /**
             * Page size (1–100)
             *
             * @example
             * 10
             */
            limit?: number;
        };

        export type Result =
            | { status: 200; body: {
                users: Array<User>;
                total: number;
            }; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace UsersExportUsers {
        export type Result =
            | { status: 200; body: string; headers: Record<string, string> };
    }

    export namespace UsersUserBadge {
        export type Params = {
            id: UserId;
        };

        export type Result =
            | { status: 200; body: Uint8Array; headers: Record<string, string> }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace UsersLastSessionEvent {
        export type Params = {
            id: UserId;
        };

        export type Result =
            | { status: 200; body: UserSessionEvent; headers: Record<string, string> }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace UsersSearchUsers {
        export type Query = {
            q: string;
            limit: number;
            cursor: number;
        };

        export type Result =
            | { status: 200; body: {
                users: Array<User>;
                nextCursor: number | null;
            }; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace UsersGetUser {
        export type Params = {
            id: UserId;
        };

        export type Headers = {
            "x-request-id": string;
        };

        export type Result =
            | { status: 200; body: User; headers: {
                "x-request-id"?: string;
            } }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace UsersUserActivity {
        export type Params = {
            id: UserId;
            year: number;
        };

        export type Result =
            | { status: 200; body: {
                userId: UserId;
                year: number;
                events: number;
            }; headers: Record<string, string> }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace UsersUserProfile {
        export type Params = {
            id: UserId;
        };

        export type Result =
            | { status: 200; body: User; headers: Record<string, string> }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace UsersCreateUser {
        export type Body = CreateUserInput;

        export type Result =
            | { status: 201; body: User; headers: Record<string, string> }
            | { status: 400; body: ProblemDetails | ValidationError; headers: Record<string, string> };
    }

    export namespace UsersDeleteUser {
        export type Params = {
            id: UserId;
        };

        export type Result =
            | { status: 200; body: {
                success: boolean;
            }; headers: Record<string, string> }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace UsersArchiveUser {
        export type Params = {
            id: UserId;
        };

        export type Result =
            | { status: 200; body: {
                alreadyArchived: true;
                userId: UserId;
            }; headers: Record<string, string> }
            | { status: 201; body: {
                archivedAt: string;
                userId: UserId;
            }; headers: Record<string, string> };
    }

    export namespace UsersUploadAvatar {
        export type Body = {
            file: File | Blob;
            userId: string;
        };

        export type Result =
            | { status: 200; body: {
                size: number;
                userId: string;
            }; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace UsersPingUser {
        export type Params = {
            id: UserId;
        };

        export type Result =
            | { status: 204; body: undefined; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace UsersGetMyWork {
        export type Result =
            | { status: 200; body: {
                items: Array<string>;
                contentType: "image/jpeg" | "text-plain" | "video.mp4" | "3d-model";
            }; headers: Record<string, string> }
            | { status: 204; body: undefined; headers: Record<string, string> };
    }

    export namespace UsersCheckUser {
        export type Params = {
            id: UserId;
        };

        export type Result =
            | { status: 200; body: {
                exists: boolean;
            }; headers: Record<string, string> }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace UsersDescribeUsers {
        export type Result =
            | { status: 200; body: {
                allow: string;
            }; headers: Record<string, string> };
    }

    export namespace HealthCheck {
        export type Result =
            | { status: 200; body: {
                ok: boolean;
            }; headers: Record<string, string> };
    }

    export namespace HealthVersion {
        export type Result =
            | { status: 200; body: {
                version: string;
            }; headers: Record<string, string> };
    }

    export namespace HealthHistory {
        export type Result =
            | { status: 200; body: Array<{
                ok: boolean;
                checkedAt: string;
            }>; headers: Record<string, string> };
    }

    export namespace NotificationsSendNotification {
        export type Body = NotificationEvent;

        export type Result =
            | { status: 202; body: {
                accepted: boolean;
            }; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace NotificationsListEvents {
        export type Query = {
            /**
             * Lower bound for occurredAt, wire format is ISO-8601
             */
            since?: string;
            kind?: EventKind;
            /**
             * Filter by id; repeated query param
             */
            ids?: Array<string>;
            /**
             * Arbitrary label, exercises z.string().transform()
             */
            label?: string;
            /**
             * One or many tag IDs, exercises non-discriminated union codegen
             */
            tagIds?: Array<string> | string;
        };

        export type Result =
            | { status: 200; body: {
                events: Array<EventRecord>;
                echo: {
                    since: string | null;
                    kind: EventKind | null;
                    ids: Array<string> | null;
                    label: string | null;
                    tagIds: Array<string> | null;
                    sessionId: string | null;
                };
            }; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace NotificationsValidateConfig {
        export type Body = {
            default: string;
            interval: number;
        };

        export type Result =
            | { status: 200; body: {
                status: string;
            }; headers: Record<string, string> }
            | { status: 400; body: ProblemDetails | ValidationError; headers: Record<string, string> }
            | { status: 401; body: undefined; headers: Record<string, string> };
    }

    export namespace NotificationsWebhook {
        export type Body = unknown;

        export type Result =
            | { status: 200; body: {
                received: boolean;
            }; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace MembersListMembers {
        export type Result =
            | { status: 200; body: {
                members: Array<User>;
            }; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: {
                "www-authenticate": string;
            } }
            | { status: 403; body: GuardDenial; headers: Record<string, string> };
    }

    export namespace MembersInviteMember {
        export type Body = {
            email: string;
        };

        export type Result =
            | { status: 201; body: User; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: {
                "www-authenticate"?: string;
            } }
            | { status: 403; body: GuardDenial; headers: Record<string, string> }
            | { status: 409; body: ProblemDetails; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace MembersCancelInvite {
        export type Params = {
            inviteId: string;
        };

        export type Result =
            | { status: 200; body: {
                cancelled: boolean;
            }; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: {
                "www-authenticate"?: string;
            } }
            | { status: 403; body: GuardDenial; headers: Record<string, string> }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace WorkspaceGetWorkspace {
        export type Result =
            | { status: 200; body: {
                id: string;
                name: string;
            }; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: Record<string, string> }
            | { status: 403; body: GuardDenial; headers: Record<string, string> };
    }

    export namespace WorkspaceDeleteWorkspace {
        export type Result =
            | { status: 200; body: {
                ok: boolean;
            }; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: Record<string, string> }
            | { status: 403; body: GuardDenial; headers: Record<string, string> };
    }

    export namespace WorkspaceTransfer {
        export type Body = {
            toUserId: string;
        };

        export type Result =
            | { status: 200; body: {
                ok: boolean;
            }; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: Record<string, string> }
            | { status: 403; body: GuardDenial; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace InvitesGetInvite {
        export type Params = {
            token: string;
        };

        export type Result =
            | { status: 200; body: {
                inviteId: string;
                email: string;
            }; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: Record<string, string> }
            | { status: 403; body: GuardDenial; headers: Record<string, string> }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> };
    }

    export namespace InvitesAcceptInvite {
        export type Params = {
            token: string;
        };

        export type Body = {
            name: string;
        };

        export type Result =
            | { status: 201; body: {
                userId: string;
            }; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: Record<string, string> }
            | { status: 403; body: GuardDenial; headers: Record<string, string> }
            | { status: 404; body: ProblemDetails; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace AssistantReply {
        export type Body = {
            prompt: string;
        };

        export type Result =
            | { status: 200; body: AsyncIterable<{ event: 'delta'; data: {
                text: string;
            }; id?: string; retry?: number } | { event: 'done'; data: {
                inputTokens: number;
                outputTokens: number;
            }; id?: string; retry?: number } | { event: 'tool_call'; data: {
                id: string;
                name: "getForecast";
                needsApproval?: true;
                input: {
                    params: {
                        city: string;
                    };
                    query: {
                        unit?: "celsius" | "fahrenheit";
                    };
                };
            } | {
                id: string;
                name: "plotSignups";
                needsApproval?: true;
                input: {
                    query: {
                        days: number;
                    };
                };
            } | {
                id: string;
                name: "countWords";
                needsApproval?: true;
                input: {
                    body: {
                        text: string;
                    };
                };
            }; id?: string; retry?: number } | { event: 'tool_result'; data: {
                id: string;
                name: "getForecast";
                output: {
                    temperature: number;
                    unit: "celsius" | "fahrenheit";
                    summary: string;
                };
            } | {
                id: string;
                name: "plotSignups";
                output: {
                    points: Array<{
                        date: string;
                        signups: number;
                    }>;
                };
            } | {
                id: string;
                name: "countWords";
                output: {
                    words: number;
                };
            }; id?: string; retry?: number } | { event: 'tool_error'; data: {
                id: string;
                name: "getForecast" | "plotSignups" | "countWords";
                message: string;
            }; id?: string; retry?: number }>; headers: Record<string, string> }
            | { status: 400; body: ProblemDetails | ValidationError; headers: Record<string, string> };
    }

    export namespace AssistantChat {
        export type Body = {
            prompt: string;
            answer?: {
                call: {
                    id: string;
                    name: string;
                    input?: unknown;
                };
                approved: boolean;
            };
        };

        export type Result =
            | { status: 200; body: AsyncIterable<{ event: 'delta'; data: {
                text: string;
            }; id?: string; retry?: number } | { event: 'tool_call'; data: {
                id: string;
                name: "notes.list";
                needsApproval?: true;
            } | {
                id: string;
                name: "notes.add";
                needsApproval?: true;
                input: {
                    body: {
                        text: string;
                    };
                };
            }; id?: string; retry?: number } | { event: 'tool_result'; data: {
                id: string;
                name: "notes.list";
                output: {
                    notes: Array<{
                        id: string;
                        text: string;
                    }>;
                };
            } | {
                id: string;
                name: "notes.add";
                output: {
                    id: string;
                    text: string;
                };
            }; id?: string; retry?: number } | { event: 'tool_error'; data: {
                id: string;
                name: "notes.list" | "notes.add";
                message: string;
            }; id?: string; retry?: number }>; headers: Record<string, string> }
            | { status: 400; body: ProblemDetails | ValidationError; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: {
                "www-authenticate": string;
            } }
            | { status: 403; body: GuardDenial; headers: Record<string, string> };
    }

    export namespace ToolsGetForecast {
        export type Params = {
            city: string;
        };

        export type Query = {
            unit?: "celsius" | "fahrenheit";
        };

        export type Result =
            | { status: 200; body: {
                temperature: number;
                unit: "celsius" | "fahrenheit";
                summary: string;
            }; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace ToolsPlotSignups {
        export type Query = {
            days: number;
        };

        export type Result =
            | { status: 200; body: {
                points: Array<{
                    date: string;
                    signups: number;
                }>;
            }; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace ToolsCountWords {
        export type Body = {
            text: string;
        };

        export type Result =
            | { status: 200; body: {
                words: number;
            }; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace NotesList {
        export type Result =
            | { status: 200; body: {
                notes: Array<{
                    id: string;
                    text: string;
                }>;
            }; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: {
                "www-authenticate": string;
            } }
            | { status: 403; body: GuardDenial; headers: Record<string, string> };
    }

    export namespace NotesAdd {
        export type Body = {
            text: string;
        };

        export type Result =
            | { status: 201; body: {
                id: string;
                text: string;
            }; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: {
                "www-authenticate": string;
            } }
            | { status: 403; body: GuardDenial; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace DiagnosticsWhoAmI {
        export type Result =
            | { status: 200; body: {
                path: string;
                method: string;
                userAgent: string | null;
            }; headers: Record<string, string> };
    }

    export namespace ProductsListProducts {
        export type Query = {
            q?: string;
        };

        export type Result =
            | { status: 200; body: {
                products: Array<Product>;
            }; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace ProductsListProductOptions {
        export type Query = {
            q?: string;
            ids?: Array<ProductId>;
        };

        export type Result =
            | { status: 200; body: {
                options: Array<{
                    id: ProductId;
                    label: string;
                    image?: string;
                }>;
            }; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace ProductsGetProduct {
        export type Params = {
            id: ProductId;
        };

        export type Result =
            | { status: 200; body: Product; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: {
                "www-authenticate"?: string;
            } }
            | { status: 403; body: GuardDenial; headers: Record<string, string> };
    }

    export namespace ProductsUpdateProduct {
        export type Params = {
            id: ProductId;
        };

        export type Body = {
            name: string;
        };

        export type Result =
            | { status: 200; body: Product; headers: Record<string, string> }
            | { status: 401; body: GuardDenial; headers: {
                "www-authenticate": string;
            } }
            | { status: 403; body: GuardDenial; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }

    export namespace ContactSend {
        export type Body = {
            name: string;
            email: string;
            message: string;
        };

        export type Result =
            | { status: 204; body: undefined; headers: Record<string, string> }
            | { status: 400; body: ValidationError; headers: Record<string, string> };
    }
}

export interface Client {
    users: {
        /**
         * List users with pagination
         *
         * @example
         * const result = await client.users.listUsers();
         */
        listUsers: ClientMethod<'GET', false, {
            query?: API.UsersListUsers.Query;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.UsersListUsers.Result>;
        /**
         * Export users as CSV, exercises a non-JSON (text/csv) raw response body
         *
         * @example
         * const result = await client.users.exportUsers();
         */
        exportUsers: ClientMethod<'GET', false, {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.UsersExportUsers.Result>;
        /**
         * Download a user badge, exercises a binary (BinarySchema) response body under a cache policy and an ETag
         *
         * @example
         * const result = await client.users.userBadge({
         *     params: {
         *         id: '1',
         *     },
         * });
         */
        userBadge: ClientMethod<'GET', false, {
            params: API.UsersUserBadge.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.UsersUserBadge.Result>;
        /**
         * A user's most recent login or logout, inline union variants nest under the User model in native clients
         *
         * @example
         * const result = await client.users.lastSessionEvent({
         *     params: {
         *         id: '1',
         *     },
         * });
         */
        lastSessionEvent: ClientMethod<'GET', false, {
            params: API.UsersLastSessionEvent.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.UsersLastSessionEvent.Result>;
        /**
         * Search users, required coerced limit and cursor
         *
         * @example
         * const result = await client.users.searchUsers({
         *     query: {
         *         q: 'string',
         *         limit: 1,
         *         cursor: 1,
         *     },
         * });
         */
        searchUsers: ClientMethod<'GET', false, {
            query: API.UsersSearchUsers.Query;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.UsersSearchUsers.Result>;
        /**
         * Get a user by id
         *
         * @example
         * const result = await client.users.getUser({
         *     params: {
         *         id: '1',
         *     },
         *     headers: {
         *         "x-request-id": '1',
         *     },
         * });
         */
        getUser: ClientMethod<'GET', false, {
            params: API.UsersGetUser.Params;
            headers: API.UsersGetUser.Headers;
            fetchOptions?: RequestInit;
        }, API.UsersGetUser.Result>;
        /**
         * Get a year of user activity, exercising two typed path params (a branded id and a coerced int year) and a cache policy on both a success and an error response
         *
         * @example
         * const result = await client.users.userActivity({
         *     params: {
         *         id: '1',
         *         year: 1,
         *     },
         * });
         */
        userActivity: ClientMethod<'GET', false, {
            params: API.UsersUserActivity.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.UsersUserActivity.Result>;
        /**
         * Get a user profile, exercises an ETag and the 304 a matching If-None-Match answers with
         *
         * @example
         * const result = await client.users.userProfile({
         *     params: {
         *         id: '1',
         *     },
         * });
         */
        userProfile: ClientMethod<'GET', false, {
            params: API.UsersUserProfile.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.UsersUserProfile.Result>;
        /**
         * Create a user
         *
         * @example
         * const result = await client.users.createUser({
         *     body: {
         *         name: 'Alice Johnson',
         *         email: 'alice@example.com',
         *     },
         * });
         */
        createUser: ClientMethod<'POST', false, {
            body: API.UsersCreateUser.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.UsersCreateUser.Result>;
        /**
         * Delete a user
         *
         * @deprecated use `archiveUser` instead
         *
         * @example
         * const result = await client.users.deleteUser({
         *     params: {
         *         id: '1',
         *     },
         * });
         */
        deleteUser: ClientMethod<'DELETE', false, {
            params: API.UsersDeleteUser.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.UsersDeleteUser.Result>;
        /**
         * Archive a user, first call returns 201, subsequent calls 200
         *
         * @example
         * const result = await client.users.archiveUser({
         *     params: {
         *         id: '1',
         *     },
         * });
         */
        archiveUser: ClientMethod<'POST', false, {
            params: API.UsersArchiveUser.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.UsersArchiveUser.Result>;
        /**
         * Upload an avatar image
         *
         * @example
         * const result = await client.users.uploadAvatar({
         *     body: {
         *         file: new File([], 'upload.txt'),
         *         userId: '1',
         *     },
         * });
         */
        uploadAvatar: ClientMethod<'POST', false, {
            body: API.UsersUploadAvatar.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.UsersUploadAvatar.Result>;
        /**
         * Ping a user, exercises z.void() body and response
         *
         * @example
         * const result = await client.users.pingUser({
         *     params: {
         *         id: '1',
         *     },
         * });
         */
        pingUser: ClientMethod<'POST', false, {
            params: API.UsersPingUser.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.UsersPingUser.Result>;
        /**
         * List work items, exercises a z.void() arm in a multi-status success union and enum values that are not valid Swift identifiers
         *
         * @example
         * const result = await client.users.getMyWork();
         */
        getMyWork: ClientMethod<'GET', false, {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.UsersGetMyWork.Result>;
        /**
         * Check user existence, exercises HEAD body stripping
         *
         * @example
         * const result = await client.users.checkUser({
         *     params: {
         *         id: '1',
         *     },
         * });
         */
        checkUser: ClientMethod<'HEAD', false, {
            params: API.UsersCheckUser.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.UsersCheckUser.Result>;
        /**
         * Describe allowed operations, exercises OPTIONS routing
         *
         * @example
         * const result = await client.users.describeUsers();
         */
        describeUsers: ClientMethod<'OPTIONS', false, {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.UsersDescribeUsers.Result>;
    };
    health: {
        /**
         * Health check, exercises nested sub-client routing
         *
         * @example
         * const result = await client.health.check();
         */
        check: ClientMethod<'GET', false, {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.HealthCheck.Result>;
        /**
         * Version, exercises second method in a sub-client group
         *
         * @example
         * const result = await client.health.version();
         */
        version: ClientMethod<'GET', false, {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.HealthVersion.Result>;
        /**
         * Health history, exercises array return type qualification
         *
         * @example
         * const result = await client.health.history();
         */
        history: ClientMethod<'GET', false, {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.HealthHistory.Result>;
    };
    notifications: {
        /**
         * Send a notification (discriminated by channel)
         *
         * @example
         * const result = await client.notifications.sendNotification({
         *     body: {
         *         channel: 'email',
         *         to: 'ada@example.com',
         *         subject: 'string',
         *     },
         * });
         */
        sendNotification: ClientMethod<'POST', false, {
            body: API.NotificationsSendNotification.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.NotificationsSendNotification.Result>;
        /**
         * List events, exercises Date / enum / array query params
         *
         * @example
         * const result = await client.notifications.listEvents();
         */
        listEvents: ClientMethod<'GET', false, {
            query?: API.NotificationsListEvents.Query;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.NotificationsListEvents.Result>;
        /**
         * Validate schemas, exercises generator bug coverage
         *
         * @example
         * const result = await client.notifications.validateConfig({
         *     body: {
         *         default: 'string',
         *         interval: 1,
         *     },
         * });
         */
        validateConfig: ClientMethod<'POST', false, {
            body: API.NotificationsValidateConfig.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.NotificationsValidateConfig.Result>;
        /**
         * Receive arbitrary webhook payload, exercises z.any() / AnyCodable codegen
         *
         * @example
         * const result = await client.notifications.webhook({
         *     body: undefined,
         * });
         */
        webhook: ClientMethod<'POST', false, {
            body: API.NotificationsWebhook.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.NotificationsWebhook.Result>;
    };
    members: {
        /**
         * List workspace members
         *
         * @example
         * const result = await client.members.listMembers();
         */
        listMembers: ClientMethod<'GET', false, {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.MembersListMembers.Result>;
        /**
         * Invite a member to the workspace
         *
         * @example
         * const result = await client.members.inviteMember({
         *     body: {
         *         email: 'ada@example.com',
         *     },
         * });
         */
        inviteMember: ClientMethod<'POST', false, {
            body: API.MembersInviteMember.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.MembersInviteMember.Result>;
        /**
         * Cancel an invite, an admin only their own
         *
         * @example
         * const result = await client.members.cancelInvite({
         *     params: {
         *         inviteId: '1',
         *     },
         * });
         */
        cancelInvite: ClientMethod<'DELETE', false, {
            params: API.MembersCancelInvite.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.MembersCancelInvite.Result>;
    };
    workspace: {
        /**
         * Get workspace info
         *
         * @example
         * const result = await client.workspace.getWorkspace();
         */
        getWorkspace: ClientMethod<'GET', false, {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.WorkspaceGetWorkspace.Result>;
        /**
         * Delete the workspace, owner only
         *
         * @example
         * const result = await client.workspace.deleteWorkspace();
         */
        deleteWorkspace: ClientMethod<'DELETE', false, {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.WorkspaceDeleteWorkspace.Result>;
        /**
         * Transfer ownership, owner only
         *
         * @example
         * const result = await client.workspace.transfer({
         *     body: {
         *         toUserId: '1',
         *     },
         * });
         */
        transfer: ClientMethod<'POST', false, {
            body: API.WorkspaceTransfer.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.WorkspaceTransfer.Result>;
    };
    invites: {
        /**
         * Resolve an invite by its capability-URL token, guarded by a custom path-token identity
         *
         * @example
         * const result = await client.invites.getInvite({
         *     params: {
         *         token: '1',
         *     },
         * });
         */
        getInvite: ClientMethod<'GET', false, {
            params: API.InvitesGetInvite.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.InvitesGetInvite.Result>;
        /**
         * Accept an invite via the capability URL
         *
         * @example
         * const result = await client.invites.acceptInvite({
         *     params: {
         *         token: '1',
         *     },
         *     body: {
         *         name: 'string',
         *     },
         * });
         */
        acceptInvite: ClientMethod<'POST', false, {
            params: API.InvitesAcceptInvite.Params;
            body: API.InvitesAcceptInvite.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.InvitesAcceptInvite.Result>;
    };
    assistant: {
        /**
         * Stream an assistant reply, exercises a server-sent events response
         *
         * @example
         * const result = await client.assistant.reply({
         *     body: {
         *         prompt: 'string',
         *     },
         * });
         */
        reply: ClientMethod<'POST', true, {
            body: API.AssistantReply.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.AssistantReply.Result>;
        /**
         * Chat with an assistant that keeps notes for the signed-in user, exercises tools on a stream
         *
         * @example
         * const result = await client.assistant.chat({
         *     body: {
         *         prompt: 'string',
         *     },
         * });
         */
        chat: ClientMethod<'POST', true, {
            body: API.AssistantChat.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.AssistantChat.Result>;
    };
    tools: {
        /**
         * Look up tomorrow forecast for one city
         *
         * @example
         * const result = await client.tools.getForecast({
         *     params: {
         *         city: 'string',
         *     },
         * });
         */
        getForecast: ClientMethod<'GET', false, {
            params: API.ToolsGetForecast.Params;
            query?: API.ToolsGetForecast.Query;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.ToolsGetForecast.Result>;
        /**
         * Plot signups per day over the last N days, for the client to draw as a chart
         *
         * @example
         * const result = await client.tools.plotSignups({
         *     query: {
         *         days: 1,
         *     },
         * });
         */
        plotSignups: ClientMethod<'GET', false, {
            query: API.ToolsPlotSignups.Query;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.ToolsPlotSignups.Result>;
        /**
         * Count the words in a piece of text
         *
         * @example
         * const result = await client.tools.countWords({
         *     body: {
         *         text: 'string',
         *     },
         * });
         */
        countWords: ClientMethod<'POST', false, {
            body: API.ToolsCountWords.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.ToolsCountWords.Result>;
    };
    notes: {
        /**
         * List the notes the signed-in user has saved
         *
         * @example
         * const result = await client.notes.list();
         */
        list: ClientMethod<'GET', false, {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.NotesList.Result>;
        /**
         * Save a note for the signed-in user
         *
         * @example
         * const result = await client.notes.add({
         *     body: {
         *         text: 'string',
         *     },
         * });
         */
        add: ClientMethod<'POST', false, {
            body: API.NotesAdd.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.NotesAdd.Result>;
    };
    diagnostics: {
        /**
         * Report the caller as Next sees it
         *
         * @example
         * const result = await client.diagnostics.whoAmI();
         */
        whoAmI: ClientMethod<'GET', false, {
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.DiagnosticsWhoAmI.Result>;
    };
    products: {
        /**
         * List products, optionally matching a search
         *
         * @example
         * const result = await client.products.listProducts();
         */
        listProducts: ClientMethod<'GET', false, {
            query?: API.ProductsListProducts.Query;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.ProductsListProducts.Result>;
        /**
         * List products by name and thumbnail, for the CMS editor's picker
         *
         * @example
         * const result = await client.products.listProductOptions();
         */
        listProductOptions: ClientMethod<'GET', false, {
            query?: API.ProductsListProductOptions.Query;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.ProductsListProductOptions.Result>;
        /**
         * Read one product, as the site or the staff
         *
         * @example
         * const result = await client.products.getProduct({
         *     params: {
         *         id: '1',
         *     },
         * });
         */
        getProduct: ClientMethod<'GET', false, {
            params: API.ProductsGetProduct.Params;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.ProductsGetProduct.Result>;
        /**
         * Rename a product and refresh every page featuring it
         *
         * @example
         * const result = await client.products.updateProduct({
         *     params: {
         *         id: '1',
         *     },
         *     body: {
         *         name: 'string',
         *     },
         * });
         */
        updateProduct: ClientMethod<'PATCH', false, {
            params: API.ProductsUpdateProduct.Params;
            body: API.ProductsUpdateProduct.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.ProductsUpdateProduct.Result>;
    };
    contact: {
        /**
         * Send a message from the contact form
         *
         * @example
         * const result = await client.contact.send({
         *     body: {
         *         name: 'string',
         *         email: 'ada@example.com',
         *         message: 'string',
         *     },
         * });
         */
        send: ClientMethod<'POST', false, {
            body: API.ContactSend.Body;
            headers?: Record<string, string>;
            fetchOptions?: RequestInit;
        }, API.ContactSend.Result>;
    };
}

const routes: GeneratedRoutes = {
    users: {
        listUsers: {
            method: 'GET',
            path: '/users',
            responses: {
                200: {},
                400: {},
            },
        },
        exportUsers: {
            method: 'GET',
            path: '/users/export',
            responses: {
                200: {},
            },
        },
        userBadge: {
            method: 'GET',
            path: '/users/:id/badge',
            responses: {
                200: {},
                404: {},
            },
        },
        lastSessionEvent: {
            method: 'GET',
            path: '/users/:id/last-session-event',
            responses: {
                200: {},
                404: {},
            },
        },
        searchUsers: {
            method: 'GET',
            path: '/users/search',
            responses: {
                200: {},
                400: {},
            },
        },
        getUser: {
            method: 'GET',
            path: '/users/:id',
            responses: {
                200: {},
                404: {},
            },
        },
        userActivity: {
            method: 'GET',
            path: '/users/:id/activity/:year',
            responses: {
                200: {},
                404: {},
            },
        },
        userProfile: {
            method: 'GET',
            path: '/users/:id/profile',
            responses: {
                200: {},
                404: {},
            },
        },
        createUser: {
            method: 'POST',
            path: '/users',
            responses: {
                201: {},
                400: {},
            },
        },
        deleteUser: {
            method: 'DELETE',
            path: '/users/:id',
            responses: {
                200: {},
                404: {},
            },
        },
        archiveUser: {
            method: 'POST',
            path: '/users/:id/archive',
            responses: {
                200: {},
                201: {},
            },
        },
        uploadAvatar: {
            method: 'POST',
            path: '/avatar',
            contentType: 'multipart/form-data',
            responses: {
                200: {},
                400: {},
            },
        },
        pingUser: {
            method: 'POST',
            path: '/users/:id/ping',
            responses: {
                204: {},
                400: {},
            },
        },
        getMyWork: {
            method: 'GET',
            path: '/work',
            responses: {
                200: {},
                204: {},
            },
        },
        checkUser: {
            method: 'HEAD',
            path: '/users/:id/check',
            responses: {
                200: {},
                404: {},
            },
        },
        describeUsers: {
            method: 'OPTIONS',
            path: '/users/describe',
            responses: {
                200: {},
            },
        },
    },
    health: {
        check: {
            method: 'GET',
            path: '/health',
            responses: {
                200: {},
            },
        },
        version: {
            method: 'GET',
            path: '/health/version',
            responses: {
                200: {},
            },
        },
        history: {
            method: 'GET',
            path: '/health/history',
            responses: {
                200: {},
            },
        },
    },
    notifications: {
        sendNotification: {
            method: 'POST',
            path: '/notifications',
            responses: {
                202: {},
                400: {},
            },
        },
        listEvents: {
            method: 'GET',
            path: '/events',
            responses: {
                200: {},
                400: {},
            },
        },
        validateConfig: {
            method: 'POST',
            path: '/schemas/validate',
            responses: {
                200: {},
                400: {},
                401: {},
            },
        },
        webhook: {
            method: 'POST',
            path: '/webhook',
            responses: {
                200: {},
                400: {},
            },
        },
    },
    members: {
        listMembers: {
            method: 'GET',
            path: '/workspace/members',
            responses: {
                200: {},
                401: {},
                403: {},
            },
        },
        inviteMember: {
            method: 'POST',
            path: '/workspace/members',
            responses: {
                201: {},
                401: {},
                403: {},
                409: {},
                400: {},
            },
        },
        cancelInvite: {
            method: 'DELETE',
            path: '/workspace/invites/:inviteId',
            responses: {
                200: {},
                401: {},
                403: {},
                404: {},
            },
        },
    },
    workspace: {
        getWorkspace: {
            method: 'GET',
            path: '/workspace',
            responses: {
                200: {},
                401: {},
                403: {},
            },
        },
        deleteWorkspace: {
            method: 'DELETE',
            path: '/workspace',
            responses: {
                200: {},
                401: {},
                403: {},
            },
        },
        transfer: {
            method: 'POST',
            path: '/workspace/transfer',
            responses: {
                200: {},
                401: {},
                403: {},
                400: {},
            },
        },
    },
    invites: {
        getInvite: {
            method: 'GET',
            path: '/invites/:token',
            responses: {
                200: {},
                401: {},
                403: {},
                404: {},
            },
        },
        acceptInvite: {
            method: 'POST',
            path: '/invites/:token/accept',
            responses: {
                201: {},
                401: {},
                403: {},
                404: {},
                400: {},
            },
        },
    },
    assistant: {
        reply: {
            method: 'POST',
            path: '/assistant/reply',
            responses: {
                200: { stream: true, contentType: 'text/event-stream' },
                400: {},
            },
        },
        chat: {
            method: 'POST',
            path: '/assistant/chat',
            responses: {
                200: { stream: true, contentType: 'text/event-stream' },
                400: {},
                401: {},
                403: {},
            },
        },
    },
    tools: {
        getForecast: {
            method: 'GET',
            path: '/forecast/:city',
            responses: {
                200: {},
                400: {},
            },
        },
        plotSignups: {
            method: 'GET',
            path: '/signups',
            responses: {
                200: {},
                400: {},
            },
        },
        countWords: {
            method: 'POST',
            path: '/text/word-count',
            responses: {
                200: {},
                400: {},
            },
        },
    },
    notes: {
        list: {
            method: 'GET',
            path: '/notes',
            responses: {
                200: {},
                401: {},
                403: {},
            },
        },
        add: {
            method: 'POST',
            path: '/notes',
            responses: {
                201: {},
                401: {},
                403: {},
                400: {},
            },
        },
    },
    diagnostics: {
        whoAmI: {
            method: 'GET',
            path: '/diagnostics/caller',
            responses: {
                200: {},
            },
        },
    },
    products: {
        listProducts: {
            method: 'GET',
            path: '/products',
            responses: {
                200: {},
                400: {},
            },
        },
        listProductOptions: {
            method: 'GET',
            path: '/product-options',
            responses: {
                200: {},
                400: {},
            },
        },
        getProduct: {
            method: 'GET',
            path: '/products/:id',
            responses: {
                200: {},
                401: {},
                403: {},
            },
        },
        updateProduct: {
            method: 'PATCH',
            path: '/products/:id',
            responses: {
                200: {},
                401: {},
                403: {},
                400: {},
            },
        },
    },
    contact: {
        send: {
            method: 'POST',
            path: '/contact',
            responses: {
                204: {},
                400: {},
            },
        },
    },
};

/**
 * Brands a value from outside the API, like a URL segment, as `API.UserId`. A value from a response is branded already.
 *
 * @example
 * const id = toUserId('usr_abc123');
 */
export const toUserId = (value: string): API.UserId => value as API.UserId;

/**
 * Brands a value from outside the API, like a URL segment, as `API.ProductId`. A value from a response is branded already.
 *
 * @example
 * const id = toProductId('1');
 */
export const toProductId = (value: string): API.ProductId => value as API.ProductId;

/**
 * Whether a `400` body is the validation error kizuna sends, rather than a `400` the route declares itself.
 *
 * @example
 * if (result.status === 400 && isValidationError(result.body)) {
 *     console.log(result.body.errors);
 * }
 */
export const isValidationError = (body: unknown): body is API.ValidationError =>
    typeof body === 'object' && body !== null && 'errors' in body && Array.isArray(body.errors);

export interface RequestContext {
    "x-posthog-session-id"?: string;
    "x-posthog-distinct-id"?: string;
}

/**
 * A client for this API. Pass the base URL, the request context headers this
 * API declares, and anything else the runtime takes.
 */
export const createClient = (config: ClientConfig & { requestContext?: RequestContext }): Client =>
    buildClient(routes, config) as unknown as Client;

/**
 * What the client knows about one response: nothing for a body it reads as
 * JSON, the media type for one that streams.
 */
export type GeneratedResponse =
    | Record<string, never>
    | {
          stream: true;
          contentType: string;
      };

/**
 * One route in the table: how to reach it, and how to read each status it
 * answers with.
 */
export interface GeneratedRoute {
    method: string;
    path: string;
    contentType?: string;
    responses: Record<number, GeneratedResponse>;
}

/**
 * The route table, nested the way the client is.
 */
export interface GeneratedRoutes {
    [key: string]: GeneratedRoutes | GeneratedRoute;
}

/**
 * The request onRequest receives before it is sent. A header set on headers
 * is sent with it.
 */
export interface OutgoingRequest {
    url: string;
    method: string;
    headers: Headers;
    route: GeneratedRoute;
}

/**
 * Where the client sends its requests, and what it adds to each one.
 */
export interface ClientConfig {
    baseUrl: string;
    baseHeaders?: Record<string, string>;
    credentials?: RequestCredentials;
    fetch?: typeof fetch;
    onRequest?: (request: OutgoingRequest) => void | Promise<void>;
}

/**
 * One method on the client. Its '~route' names the method it sends and
 * whether its response streams, so a wrapper like @kizunajs/tanstack-query
 * reads both off the client.
 */
export type ClientMethod<Method extends string, Streams extends boolean, Args, Result> = ({} extends Args
    ? (args?: Args) => Promise<Result>
    : (args: Args) => Promise<Result>) & {
    readonly '~route': GeneratedRoute & {
        readonly method: Method;
        readonly streams: Streams;
    };
};

interface CallArgs {
    params?: Record<string, unknown>;
    query?: Record<string, unknown>;
    body?: unknown;
    headers?: Record<string, string | undefined>;
    fetchOptions?: RequestInit;
}

/**
 * Dates go on the wire as ISO 8601, everything else as String gives it.
 */
const serializeValue = (value: unknown): string => (value instanceof Date ? value.toISOString() : String(value));

const buildPath = (path: string, params: Record<string, unknown> = {}): string =>
    path.replace(/:([A-Za-z_][A-Za-z0-9_]*)/g, (_, name: string) => {
        const value = params[name];
        if (value === undefined) throw new Error('Missing path parameter: ' + name);
        return encodeURIComponent(serializeValue(value));
    });

/**
 * An array repeats its key, and an undefined or null field is left out.
 */
const buildSearchParams = (fields: Record<string, unknown>): URLSearchParams => {
    const params = new URLSearchParams();
    for (const [key, value] of Object.entries(fields)) {
        if (value === undefined || value === null) continue;
        for (const item of Array.isArray(value) ? value : [value]) params.append(key, serializeValue(item));
    }
    return params;
};

const buildFormData = (fields: Record<string, unknown>): FormData => {
    const formData = new FormData();
    for (const [key, value] of Object.entries(fields)) {
        for (const item of Array.isArray(value) ? value : [value]) {
            if (item instanceof Blob) formData.append(key, item);
            else if (item !== undefined && item !== null) formData.append(key, typeof item === 'string' ? item : JSON.stringify(item));
        }
    }
    return formData;
};

/**
 * A multipart body leaves Content-Type to fetch, which adds the boundary.
 */
const encodeBody = (route: GeneratedRoute, body: unknown, headers: Headers): BodyInit => {
    switch (route.contentType) {
        case 'multipart/form-data':
            return body instanceof FormData ? body : buildFormData(body as Record<string, unknown>);
        case 'application/x-www-form-urlencoded':
            if (!headers.has('Content-Type')) headers.set('Content-Type', 'application/x-www-form-urlencoded');
            return buildSearchParams(body as Record<string, unknown>);
        default:
            if (!headers.has('Content-Type')) headers.set('Content-Type', 'application/json');
            return JSON.stringify(body);
    }
};

const parseJson = (text: string): unknown => {
    try {
        return JSON.parse(text) as unknown;
    } catch {
        return text;
    }
};

interface ServerSentEvent {
    event?: string;
    data: unknown;
    id?: string;
    retry?: number;
}

/**
 * A lone carriage return at the end may be half of CRLF, so it waits for more
 * unless the stream is over.
 */
const findLineEnd = (buffer: string, final: boolean): { index: number; length: number } | undefined => {
    for (let index = 0; index < buffer.length; index += 1) {
        const character = buffer[index];
        if (character === '\n') return { index, length: 1 };
        if (character === '\r') {
            if (index + 1 < buffer.length) return { index, length: buffer[index + 1] === '\n' ? 2 : 1 };
            if (final) return { index, length: 1 };
            return undefined;
        }
    }
    return undefined;
};

/**
 * Reads text/event-stream as the WHATWG HTML specification parses it.
 */
async function* readEvents(body: ReadableStream<Uint8Array>): AsyncGenerator<ServerSentEvent> {
    const reader = body.getReader();
    const decoder = new TextDecoder();
    let buffer = '';
    let first = true;
    let dataLines: string[] = [];
    let eventType = '';
    let lastEventId = '';
    let retry: number | undefined;

    const dispatch = (): ServerSentEvent | undefined => {
        if (dataLines.length === 0) {
            eventType = '';
            return undefined;
        }
        const message: ServerSentEvent = {
            data: parseJson(dataLines.join('\n')),
        };
        if (eventType !== '') message.event = eventType;
        if (lastEventId !== '') message.id = lastEventId;
        if (retry !== undefined) message.retry = retry;
        dataLines = [];
        eventType = '';
        retry = undefined;
        return message;
    };

    const processLine = (line: string): ServerSentEvent | undefined => {
        if (line === '') return dispatch();
        if (line.startsWith(':')) return undefined;
        const separator = line.indexOf(':');
        const field = separator === -1 ? line : line.slice(0, separator);
        let value = separator === -1 ? '' : line.slice(separator + 1);
        if (value.startsWith(' ')) value = value.slice(1);
        switch (field) {
            case 'event':
                eventType = value;
                break;
            case 'data':
                dataLines.push(value);
                break;
            case 'id':
                if (!value.includes('\0')) lastEventId = value;
                break;
            case 'retry':
                if (/^\d+$/.test(value)) retry = Number(value);
                break;
        }
        return undefined;
    };

    try {
        for (;;) {
            const { done, value } = await reader.read();
            let chunk = done ? decoder.decode() : decoder.decode(value, { stream: true });
            if (first && chunk.length > 0) {
                if (chunk.charCodeAt(0) === 0xfeff) chunk = chunk.slice(1);
                first = false;
            }
            buffer += chunk;
            for (;;) {
                const lineEnd = findLineEnd(buffer, done);
                if (lineEnd === undefined) break;
                const line = buffer.slice(0, lineEnd.index);
                buffer = buffer.slice(lineEnd.index + lineEnd.length);
                const message = processLine(line);
                if (message !== undefined) yield message;
            }
            if (done) return;
        }
    } finally {
        void reader.cancel().catch(() => undefined);
    }
}

async function* readText(body: ReadableStream<Uint8Array>): AsyncGenerator<string> {
    const reader = body.getReader();
    const decoder = new TextDecoder();
    try {
        for (;;) {
            const { done, value } = await reader.read();
            if (done) {
                const tail = decoder.decode();
                if (tail.length > 0) yield tail;
                return;
            }
            const text = decoder.decode(value, { stream: true });
            if (text.length > 0) yield text;
        }
    } finally {
        void reader.cancel().catch(() => undefined);
    }
}

async function* readBytes(body: ReadableStream<Uint8Array>): AsyncGenerator<Uint8Array> {
    const reader = body.getReader();
    try {
        for (;;) {
            const { done, value } = await reader.read();
            if (done) return;
            yield value;
        }
    } finally {
        void reader.cancel().catch(() => undefined);
    }
}

const readStream = (body: ReadableStream<Uint8Array>, contentType: string): AsyncIterable<unknown> => {
    const essence = (contentType.split(';')[0] ?? '').trim().toLowerCase();
    if (essence === 'text/event-stream') return readEvents(body);
    if (essence.startsWith('text/')) return readText(body);
    return readBytes(body);
};

const buildMethod = (route: GeneratedRoute, config: ClientConfig) => {
    const call = async (args: CallArgs = {}) => {
        const query = args.query === undefined ? '' : buildSearchParams(args.query).toString();
        const url = config.baseUrl + buildPath(route.path, args.params) + (query.length > 0 ? '?' + query : '');
        const headers = new Headers(config.baseHeaders);
        for (const [name, value] of Object.entries(args.headers ?? {})) {
            if (value !== undefined) headers.set(name, value);
        }
        const init: RequestInit = {
            method: route.method,
            headers,
        };
        if (args.body !== undefined) init.body = encodeBody(route, args.body, headers);
        if (config.credentials !== undefined) init.credentials = config.credentials;
        await config.onRequest?.({
            url,
            method: route.method,
            headers,
            route,
        });

        const response = await (config.fetch ?? fetch)(url, {
            ...init,
            ...args.fetchOptions,
        });
        const responseHeaders: Record<string, string> = {};
        response.headers.forEach((value, name) => {
            responseHeaders[name] = value;
        });
        const declared = route.responses[response.status];
        if (declared !== undefined && 'stream' in declared && response.body !== null) {
            return {
                status: response.status,
                body: readStream(response.body, declared.contentType),
                headers: responseHeaders,
            };
        }
        const text = await response.text();
        return {
            status: response.status,
            body: text.length > 0 ? parseJson(text) : undefined,
            headers: responseHeaders,
        };
    };
    const streams = Object.values(route.responses).some((response) => 'stream' in response);
    return Object.defineProperty(call, '~route', {
        value: {
            ...route,
            streams,
        },
    });
};

const isRoute = (node: GeneratedRoutes | GeneratedRoute): node is GeneratedRoute => typeof node['method'] === 'string';

const buildTree = (routes: GeneratedRoutes, config: ClientConfig): Record<string, unknown> => {
    const tree: Record<string, unknown> = {};
    for (const [key, node] of Object.entries(routes)) {
        tree[key] = isRoute(node) ? buildMethod(node, config) : buildTree(node, config);
    }
    return tree;
};

/**
 * Sends the request context headers with every request. An explicit
 * baseHeaders entry wins.
 */
const buildClient = (routes: GeneratedRoutes, config: ClientConfig & { requestContext?: object }): Record<string, unknown> => {
    const contextHeaders: Record<string, string> = {};
    for (const [name, value] of Object.entries(config.requestContext ?? {})) {
        if (value !== undefined) contextHeaders[name] = String(value);
    }
    return buildTree(routes, {
        ...config,
        baseHeaders: {
            ...contextHeaders,
            ...config.baseHeaders,
        },
    });
};
